### ISSUE TITLE
Song of Pelinal book models wrong for volumes 7 and 8

### ISSUE THREAD

**Issue by charger24** [TD-Addon/TD_Addon#104]
Volumes I-VI of the Song of Pelinal use the book model TR_book_closed_i15_AY, but volumes VII and VIII use different models. This should be fixed so that all eight books in the series use the same model.

**Comment by charger24** [comment]
The first six books also have an enchant capacity of 100, while 7 and 8 have an enchant of 0

**Comment by jamrt** [comment]
I fixed the enchantment, but they are using the same model. Something else is changing them.

**Comment by erwinlagu** [comment]
Please fix this
