### ISSUE TITLE
Incorrect INI key in Nexus description

### ISSUE THREAD

**Issue by C0rn3j** [TD-Addon/TD_Addon#108]
https://www.nexusmods.com/morrowind/mods/44537?tab=description
```
Then locate the Morrowind.ini in your Morrowind game directory, find the [Archive] section, 
add the two new BSAs (TR_Data.bsa, PT_Data.bsa), done. 
If Sky_Data.bsa is still in there, delete it. If you use OpenMW, you will need to reimport your Morrowind.ini.
```
![image](https://user-images.githubusercontent.com/1641362/114199361-843fac00-9954-11eb-8f40-9d86442dce48.png)
![image](https://user-images.githubusercontent.com/1641362/114199376-873a9c80-9954-11eb-9d68-2af36277ed57.png)

The desc should say `[Archives]` not `[Archive]`, [Archive] is a different key.

**Comment by jamrt** [comment]
Wow, embarrassing but corrected.
