### ISSUE TITLE
T_Bk_HandbookOfTheDevoutTR doesn't have <BR> in the end

### ISSUE THREAD

**Issue by DevvvvvShah** [TD-Addon/TD_Addon#113]
It's needed because Morrowind.exe does not display the last line in any given text, and this makes sure that the last line is empty.

**Comment by jamrt** [comment]
This currently suppresses a line that "Dramar Thelon lives in ____ with his wife". This should only be fixed when that NPC has actually been placed.

**Comment by antonisauren** [comment]
<br> is there in current data
