### ISSUE TITLE
T_Bk_MalahkOrcsTR has a 'typo' in the title

### ISSUE THREAD

**Issue by DevvvvvShah** [TD-Addon/TD_Addon#115]
'Malahk Orcs:Scourge of the East' is the current title. It needs a space after the colon, but there's no space for the space. Suggested fix is changing the title to 'The Malahk: Scourge of the East' for the outside name, while the correct title is inside. Just 'Malahk Orcs' for the name might work too.

Orginally posted by Fürst Thal in TR Bugtracker.

**Comment by jamrt** [comment]
Since they are already called "the Malahk" sometimes in the book, I'll go with the former.
