### ISSUE TITLE
Misspelling in Map of Aanthirin

### ISSUE THREAD

**Issue by DevvvvvShah** [TD-Addon/TD_Addon#118]
"independant" should be "independent"
Also "find hovel" is not a phrase I've ever heard before. A hovel is usually used to describe a wretched hole or shack where an extremely poor rural person might live. Finding a hovel could be what the author meant, but that also seems like really poor hospitality to offer a traveler.

Why edit: Note, this is a Tamriel_Data object. The ID is T_Bk_MapsM3-2TR

MinerMan60101Today at 12:02 AM
Also that bookart should say "To Andothren" with an arrow pointing northwest

Originally submitted by Factor in the Bugtracker
I checked, and the issues are still there.
![](https://www.tamriel-rebuilt.org/sites/default/files/bugscreens/MapofAanthirin.png)

**Comment by cheflul** [comment]
Fixed in Dillon's update
