### ISSUE TITLE
Expression error in T_Sc_Sound_AmbientInsects

### ISSUE THREAD

**Issue by DevvvvvShah** [TD-Addon/TD_Addon#120]
The script T_Sc_Sound_AmbientInsects throws a "Script Error: EXPRESSION" and will not start running if MournWeather is set to 7, i.e. between the quests "A Show of Power" and "A Mad God" in the Tribunal questline. The mechanics of this script are mostly copied from Sound_MournEnv, except that it checks if the player is in Almalexia during the ashstorm episode. It appears that this check is not working properly however, so this needs to be fixed. But I don't understand why it is included in the first place - a better idea would probably be to use a different script for Almalexia, and there are bound to be other changes required to it anyway by the time of the Almalexia redo.

Originally posted by Jonado in the bugtracker.

I didn't try it myself, but the suggested fix might be right. And I suspect this might be causing problems because there is no cell named Almalexia in TR_Mainland itself.

**Comment by jamrt** [comment]
This seems by and large a correct assessment. The script is used in the sound activator T_Glb_Sound_AmbientInsects_01, which is used all over the place (Thirr Valley, Necrom, Alt Orethan, Almalexia).

Referring to a cell that is not around at runtime is not doing it any favor and considering that we are probably not using MournWeather come overhaul, I've commented the code in question out and added a reasoning.

When the Almalexia time comes and we do overhaul that quest to affect the entire city (or region), we should use unique activators for this.
