### ISSUE TITLE
door_load_darkness00 missing collision

### ISSUE THREAD

**Issue by Dillonn241** [TD-Addon/TD_Addon#126]
This uses a black lava square and causes issues with falling into the void and third person view clipping wherever it's used. For example, Zanammu Tier One. This should be fixed Data-side for a clean fix that avoids collision boxes everywhere.

**Comment by cheflul** [comment]
just use a different door if the entrance is large enough to need collision, the crawl through space scripted doors should be used in smaller gaps that would rely on the surrounding object's collisions
