### ISSUE TITLE
Wild Boar should drop Boar Meat

### ISSUE THREAD

**Issue by RakanishuPT** [TD-Addon/TD_Addon#133]
T_Sky_Fau_Boar_01 and T_Sky_Fau_BoarDs_01 ("Wild Boar") currently have a leveled item random_boar_leather ("Bristleback Leather") as their loot.  It should be replaced with a new levelled item "T_Sky_Random_FaunBoarMeat" that uses "T_IngFood_MeatBoar_02" ("Boar Meat").

**Comment by jamrt** [comment]
Done and done. 1 Boar Meat, 20% chance of none.
