### ISSUE TITLE
Issue with a Hlaalu Modular piece

### ISSUE THREAD

**Issue by markavailable** [TD-Addon/TD_Addon#134]
T_De_SetHla_X_M_R2_Tn_Cnr_01_L has an issue with one of the sides of the lip. Shown in the image.
![screenshot018](https://user-images.githubusercontent.com/75810930/117043588-6eb36d00-acdb-11eb-8e0e-8159bf0f6771.png)

**Comment by cheflul** [comment]
appears to have been fixed at some point
