### ISSUE TITLE
Incorrect sheathing meshes

### ISSUE THREAD

**Issue by jamrt** [TD-Addon/TD_Addon#137]
The following sheathes are using old models:

- Ebony Katana
- Ebony Daikatana
- Ebony Tanto
- Ebony Wakizashi

The Daedric Broadsword sheath has an incorrect name: tr_w_daedra_bsword_sh.nif when it should be tr_w_daedric_bsword_sh.nif

Reported by Aleist3r on Discord.

**Comment by Alyst3r** [comment]
tr_w_daedra_lsword_02_sh.nif used old tr_w_daedra_lsword_02.nif, would need to be updated too, since new model of daedric longsword is different than old one. I'll probably fix all of them soon-ish.

**Comment by jamrt** [comment]
... and this he did.
