### ISSUE TITLE
T_Sky_Und_DrgrLor_01 has Summon Bonewolf spell

### ISSUE THREAD

**Issue by RakanishuPT** [TD-Addon/TD_Addon#139]
Its "bm_summonbonewolf" spell should be removed since it doesn't work in vanilla and bugs the creature in OpenMW.

**Comment by Assumeru** [comment]
FWIW, the "bugs the creature" part is actually vanilla behaviour. Actors without weapons that have a summon flee, even if they can't even use weapons.

**Comment by RakanishuPT** [comment]
What I noticed: In OpenMW, the draugr successfully casts the spell then flees ("bugs the creature" was incorrect).  In vanilla, it fails to cast the spell two or three times and then attacks the player with the sword.

**Comment by Assumeru** [comment]
When I tried this for #69 I found that the vanilla AI will never cast a spell containing the bonewolf effect (presumably there is a list of effects the AI is allowed to cast). The draugr lord just ends up casting its other spell until it runs out of magicka.

**Comment by cheflul** [comment]
Fixed in Dec 03 update
