### ISSUE TITLE
Markarth interior walls - plane needs halving

### ISSUE THREAD

**Issue by Tristior** [TD-Addon/TD_Addon#141]
The Markarth interior set walls z-fight when reversed against each other. The issue is that the plane indicated below needs to be halved in width, so that it extends no further than the vertical plane above it. The T_Nor_SetMarkarth_I_Wall_02x set has a similar issue with the gold band halfway up.

![T_Nor_SetMarkarth_I_ClrWall_01](https://user-images.githubusercontent.com/84986447/120017992-e732f280-c029-11eb-8baa-2e70c99c47c1.jpg)
![T_Nor_SetMarkarth_I_Wall_01a](https://user-images.githubusercontent.com/84986447/120017998-eb5f1000-c029-11eb-96a9-62f761b56054.jpg)

This applies to:
T_Nor_SetMarkarth_I_ClrCorn_01
T_Nor_SetMarkarth_I_ClrEnd_01
T_Nor_SetMarkarth_I_ClrHall_01
T_Nor_SetMarkarth_I_ClrSide_01
T_Nor_SetMarkarth_I_ClrTCorn_01
T_Nor_SetMarkarth_I_ClrTSide_01
T_Nor_SetMarkarth_I_ClrWall_01

T_Nor_SetMarkarth_I_Wall_01a - d
T_Nor_SetMarkarth_I_Wall_02a - d

**Comment by cheflul** [comment]
Fixed by Worsas
