### ISSUE TITLE
generic crates flagged "references persist"

### ISSUE THREAD

**Issue by hemaris-tr** [TD-Addon/TD_Addon#144]
The following`T_SkyCom_Var_` containers are flagged `references persist`. I am pretty sure that none of them should have that flag.

- T_SkyCom_Var_Cr1Ceramic
- T_SkyCom_Var_Cr1Clt
- T_SkyCom_Var_Cr1Empty
- T_SkyCom_Var_Cr1Food
- T_SkyCom_Var_Cr1Hunter1
- T_SkyCom_Var_Cr1Hunter2
- T_SkyCom_Var_Cr1OreSilv
- T_SkyCom_Var_Cr2Ceramic
- T_SkyCom_Var_Cr2Clt
- T_SkyCom_Var_Cr2Drink
- T_SkyCom_Var_Cr2Empty
- T_SkyCom_Var_Cr2Fish
- T_SkyCom_Var_Cr2Food1
- T_SkyCom_Var_Cr2Mead1
- T_SkyCom_Var_Cr2Mead2
- T_SkyCom_Var_Cr2Miner
- T_SkyCom_Var_Cr2OreSilv
- T_SkyCom_Var_Cr2Wpn1
- T_SkyCom_Var_Cr2Wpn2
- T_SkyCom_Var_Cr3Ceramic
- T_SkyCom_Var_Cr3Empty
- T_SkyCom_Var_Cr4Ceramic
- T_SkyCom_Var_Cr4Empty
- T_SkyCom_Var_Cr5Band1
- T_SkyCom_Var_Cr5Band2
- T_SkyCom_Var_Cr5Ceramic
- T_SkyCom_Var_Cr5Chpfood
- T_SkyCom_Var_Cr5Empty
- T_SkyCom_Var_Cr5MeatBeef
- T_SkyCom_Var_Cr5Milk
- T_SkyCom_Var_Cr5OreSilv
- T_SkyCom_Var_Cr5Pos
- T_SkyCom_Var_Cr6Band1
- T_SkyCom_Var_Cr6Band2
- T_SkyCom_Var_Cr6Chpfood
- T_SkyCom_Var_Cr6Empty
- T_SkyCom_Var_Cr6Ing
- T_SkyCom_Var_Cr6Meatbeef
- T_SkyCom_Var_Cr6Milk
- T_SkyCom_Var_Cr6Pos
- T_SkyCom_Var_Cr6Tool1
- T_SkyCom_Var_Cr6Tool2
- T_SkyCom_Var_Cr7Arrow1
- T_SkyCom_Var_Cr7Band1
- T_SkyCom_Var_Cr7Band2
- T_SkyCom_Var_Cr7Ceramic
- T_SkyCom_Var_Cr7Dri1
- T_SkyCom_Var_Cr7Empty
- T_SkyCom_Var_Cr7Hide
- T_SkyCom_Var_Cr7Honey
- T_SkyCom_Var_Cr7Hunter
- T_SkyCom_Var_Cr7Ing
- T_SkyCom_Var_Cr7Ivory
- T_SkyCom_Var_Cr7Kitchen
- T_SkyCom_Var_Cr7Pillow
- T_SkyCom_Var_Cr7Pos
- T_SkyCom_Var_Cr7Tool
- T_SkyCom_Var_Cr7Torch
- T_SkyCom_Var_Cr7Wpn1
- T_SkyCom_Var_Cr8Band1
- T_SkyCom_Var_Cr8Band2
- T_SkyCom_Var_Cr8Ceramic
- T_SkyCom_Var_Cr8Dri1
- T_SkyCom_Var_Cr8Empty
- T_SkyCom_Var_Cr8Hide
- T_SkyCom_Var_Cr8Ing
- T_SkyCom_Var_Cr8Ivory
- T_SkyCom_Var_Cr8Kitchen
- T_SkyCom_Var_Cr8Pillow
- T_SkyCom_Var_Cr8Pos
- T_SkyCom_Var_Cr8Salt
- T_SkyCom_Var_Cr8Tool
- T_SkyCom_Var_Cr8Torch
- T_SkyCom_Var_Cr8Wpn1
- T_SkyCom_Var_Cr9Ceramic
- T_SkyCom_Var_Cr9Clt
- T_SkyCom_Var_Cr9Dri
- T_SkyCom_Var_Cr9Empty
- T_SkyCom_Var_Cr9Fish
- T_SkyCom_Var_Cr9Food1
- T_SkyCom_Var_Cr9Mead1
- T_SkyCom_Var_Cr9Mead2
- T_SkyCom_Var_Cr9Miner
- T_SkyCom_Var_Cr9OreSilv
- T_SkyCom_Var_Cr9Wpn1
- T_SkyCom_Var_Cr9Wpn2
- T_SkyCom_Var_Sk1Arm

**Comment by hemaris-tr** [comment]
I also found a handful of non-container objects which persist and probably shouldn't.

- Static `T_Sky_Flora_BushLeaves5_03`
- Door `T_Com_Var_GateMystical_01`
- Armor `T_Rga_Lamellar_Helm_G`
- Ingredient `T_IngFlor_Hemlock_01`
- Book `T_Note_ImperialTaxNotice`

**Comment by cheflul** [comment]
Fixed in Dec 03 update
