### ISSUE TITLE
Typo in T_Bk_LineOfEmperorsPC_V08

### ISSUE THREAD

**Issue by RakanishuPT** [TD-Addon/TD_Addon#152]
Corrected text in bold & italics below ("be"):

...

I hereby wish to warn the reader against a fraudulent account of the death of Katariah by the hand of the scholar Montalius, whose rumormongering and false accusations against families of great stature should **_be_** discounted and avoided at all costs.

...

**Comment by cheflul** [comment]
Fixed in 08-16 addon
