### ISSUE TITLE
Doors use ambient region sounds

### ISSUE THREAD

**Issue by RakanishuPT** [TD-Addon/TD_Addon#156]
These doors all use ambient region sounds which should be replaced with normal door sounds:

``T_Imp_Legion_GateBig_01``
``T_Imp_Legion_GateSmall_01``
``T_Imp_Legion_GateSmall_02``
``T_Imp_LegionMw_GateStrong_01``
``T_Nor_DngBarrow_Door_01``
``T_Nor_DngBarrow_Door_02``
``T_Nor_DngBarrow_Door_03``

Vanilla ``Ex_BM_tomb_door_01`` uses "Door Stone."  The Legion doors could use "Door Heavy" or "Door Metal."

**Comment by cheflul** [comment]
Fixed in Dec 03 update
