### ISSUE TITLE
New Imp rugs' IDs are mis-assigned

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#159]
Currently the rugs are sorted alongside the much smaller common rugs. Their IDs should be re-assigned as follows:

T_Imp_Furn_Rug_03b -> T_Imp_Furn_RugBigXp_07
T_Imp_Furn_Rug_05b -> T_Imp_Furn_RugBigXp_08
T_Imp_Furn_Rug_06b -> T_Imp_Furn_RugBigXp_09
T_Imp_Furn_Rug_08b -> T_Imp_Furn_RugBigXp_10
T_Imp_Furn_Rug_09b -> T_Imp_Furn_RugBigXp_11
T_Imp_Furn_Rug_Sq_01 -> T_Imp_Furn_RugSquareXp_04

**Comment by cheflul** [comment]
already fixed?
