### ISSUE TITLE
Map of Aanthirin bookart should direct to Andothren

### ISSUE THREAD

**Issue by MinerMan60101** [TD-Addon/TD_Addon#164]
T_Bk_MapsM3-2TR's bookart should be edited to have "To Andothren" with an arrow pointing northwest
![TR_Aanthirin_Map](https://user-images.githubusercontent.com/72769878/132080705-c48eb23b-c5b4-4ca7-a2bf-1d6469645791.png)

**Comment by Kynesifnar** [comment]
Presumably fixed a while ago.
