### ISSUE TITLE
Giant Kobolds

### ISSUE THREAD

**Issue by bloche1871** [TD-Addon/TD_Addon#169]
Kobolds randomly flicker between being normal size and being gigantic. It was terrifying when i saw my first one in the foggy distance

![kobold](https://user-images.githubusercontent.com/1149090/133860554-35735b00-1087-4ae2-b5de-22f1cd5a6e97.png)

**Comment by Assumeru** [comment]
https://gitlab.com/OpenMW/openmw/-/issues/5125

**Comment by Quizzmet** [comment]
Have you found a fix for this? I followed that mentioned link but it's all a talk about bone limits- nothing I saw actually seems to help address or fix this.

**Comment by bloche1871** [comment]
Nope, I still have the issue!

**Comment by Quizzmet** [comment]
I guess you'll never get truly "surprised" by Kobolds in the meantime, at least. Bumping in hopes someone knows what to do.

**Comment by revenorror** [comment]
I gave this a look and figured out what the problem is. The Bip01 node has an unapplied scale of .08, and the creature mesh itself has a scale of 12. I tried importing it into Blender to apply the scale but it chewed the model up. Somebody with 3dsmax should be able to import it and apply the scale.

**Comment by Scottska12** [comment]
Hi there. Any news on fixing this one? It's a fairly major issue when playing SHotN and I am just wondering if anyone has been able to fix it yet?

Thanks so much.

**Comment by Kynesifnar** [comment]
This _should_ be fixed by Lamb Shark's edits which were merged a few months ago.
