### ISSUE TITLE
Relocate velothi urns to F folder and renames

### ISSUE THREAD

**Issue by MwGek** [TD-Addon/TD_Addon#171]
All Objects below are located in the 'm' folder, but should be moved to the 'f' folder. They should also be renamed to be moved to a more convenient location.
In the data files:
tr_de_urn_broke01 --> tr_furn_de_urn_broke01
tr_de_urn_broke01 
tr_de_urn_broke01 
tr_de_urn_broke01

**Comment by cheflul** [comment]
#172
