### ISSUE TITLE
OutsideBanner script applied to non-animated banner models

### ISSUE THREAD

**Issue by hemaris-tr** [TD-Addon/TD_Addon#178]
These Indoril town banners (the ones with `meshes\tr\x\tr_act_ind_…` models) have the `OutsideBanner` script attached, but their meshes are not animated.

- T_De_Set_BannerTownAkamora_01
- T_De_Set_BannerTownAlma_01
- T_De_Set_BannerTownAyemar_01
- T_De_Set_BannerTownBisandr_01
- T_De_Set_BannerTownBosmora_01
- T_De_Set_BannerTownDondril_01
- T_De_Set_BannerTownDreynim_01
- T_De_Set_BannerTownDunAka_01
- T_De_Set_BannerTownEnamorD_01
- T_De_Set_BannerTownGorne_01
- T_De_Set_BannerTownMeralag_01
- T_De_Set_BannerTownOthrens_01
- T_De_Set_BannerTownRoaDyr_01
- T_De_Set_BannerTownSailen_01
- T_De_Set_BannerTownVelothr_01

![screenshot277 copy](https://user-images.githubusercontent.com/85847041/138923223-057407bf-5b3a-4d6d-b4f5-90dbdca84802.jpg)

**Comment by cheflul** [comment]
Fixed in Dec 03 update
