### ISSUE TITLE
T_Dwe_Scrap_Cuirass

### ISSUE THREAD

**Issue by 1John418** [TD-Addon/TD_Addon#181]
[This cuirass](https://media.discordapp.net/attachments/132891272666021888/910980035530342490/Morrowind_2021-11-18_20.46.25.383.png?width=842&height=473) appears [invisible ](https://media.discordapp.net/attachments/132891272666021888/910980035530342490/Morrowind_2021-11-18_20.46.25.383.png?width=842&height=473) when you put it on a character. The player uses Roberts Better Bodies and players vanilla + MGE XE.

**Comment by cheflul** [comment]
#43
