### ISSUE TITLE
Missing words in The Truth of the Hlaalu

### ISSUE THREAD

**Issue by Assumeru** [TD-Addon/TD_Addon#188]
T_Bk_TrueIntrospectionHlaaluTR

> Our nobles lead all of houses in bringing the benefits of Imperial trade

Is either missing a "the" or has an extraneous "of".

>  in our lands, no man is want of food or gold

Pretty sure this should be "is in want of" or "is wanting for" or "wants for".

**Comment by RakanishuPT** [comment]
Fixed by [179aa92](https://github.com/TD-Addon/TD_Addon/commit/179aa92ca038d2fc8e4ea9fb14231675594fb757)
