### ISSUE TITLE
01 File Patcher subdirectory isn't actually a valid BAIN subpackage

### ISSUE THREAD

**Issue by AnyOldName3** [TD-Addon/TD_Addon#189]
The `Tamriel Data (HD)-44537-8-0-1610742775.7z` file on the Nexus has `00 Core` and `01 File Patcher` subdirectories, giving the impression it's meant to be a complex BAIN (i.e. one with multiple subpackages). However, as the `01 File Patcher` subdirectory contains no actual game data (just a `.jar` and a `.txt`), Wrye Bash ignores it as a potential subpackage, determines that `00 Core` is the only viable data directory, and treats it as (what Wrye Bash internally calls) a simple BAIN (i.e. one with a single unambiguous data directory, so what other tools might call a basic archive). This means the contents of `00 Core` gets copies straight to the `Data Files` directory, and Wrye Bash/Mash users never see that the file patcher even exists.

On the other hand, in MO2, it's correctly identified as not a basic archive (as there are files in multiple subdirectories) and not a complex BAIN (as there aren't multiple sibling directories with valid game data), so the user's given the manual installation wizard, where they're required to manually label which directory is the data directory (potentially after moving files around). This seems to freak some users out, and also make the people who come to help them think MO2 can't handle BAINs because the archive looks superficially like a complex BAIN (despite not being one).

You probably want to either:
* Change the archive in some way so Wrye Bash actually detects it as a complex BAIN.
* Move the file patcher to a separate download.
* Change the archive in some way that makes it more obviously not a BAIN.

**Comment by hemaris-tr** [comment]
Closing as fixed. Tamriel_Data v9 will have only a `00 Core` folder, with the file patcher contained in `00 Core/Docs/`. To our understanding, this resolves the BAIN detection issue.
