### ISSUE TITLE
2 missing meshes, or just an accidental leftover uncleaned ID?

### ISSUE THREAD

**Issue by cheflul** [TD-Addon/TD_Addon#193]
T_Imp_LegionMw_I_DoubleWall_01 is missing meshes/tr/i/tr_in_imp_wall_01.nif
T_B_Nor_HeadMaleSHOTN_23 is missing meshes/sky/b/t_sky_b_n_hm_23.nif
If these don't exist I will simply remove the entries from the addon.

**Comment by antonisauren** [comment]
Wall object got removed, head mesh is in there. Closing
