### ISSUE TITLE
leveled list T_Cyr_Lvl_MagicAmulets contains amulet of almsivi intervention

### ISSUE THREAD

**Issue by hemaris-tr** [TD-Addon/TD_Addon#197]
The leveled list `T_Cyr_Lvl_MagicAmulets` contains `amulet of almsivi intervention`.

**Comment by RakanishuPT** [comment]
Fixed by [179aa92](https://github.com/TD-Addon/TD_Addon/commit/179aa92ca038d2fc8e4ea9fb14231675594fb757)
