### ISSUE TITLE
Small edit to text of T_Bk_GuideToTheGuildGuidesPC

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#200]
Per conversation on #pc_lore, a small edit to the following line in T_Bk_GuideToTheGuildGuidesPC:

_Additionally, the ability to maintain multiple "marked" locations is extremely rare outside the specialized training of the Guild Guides, who at best can maintain spiritual anchors in four distinct locations._

New version should read:
_Additionally, the ability to maintain multiple "marked" locations is extremely rare outside the specialized training of the Guild Guides, the very best of whom can only maintain spiritual anchors in a handful of distinct locations._

**Comment by cheflul** [comment]
fixed in d7ef849
