### ISSUE TITLE
Wereboars can't attack

### ISSUE THREAD

**Issue by Assumeru** [TD-Addon/TD_Addon#203]
The wereboar model only has animations for hand-to-hand, but as a non-bipedal creature it can't use those.

https://project-tamriel.com/viewtopic.php?p=2850#p2850

**Comment by Alyst3r** [comment]
Seems like some problems with kf file, other variant from data (sky_wereboar_olct.nif) works correctly. Also, not being able to use hand-to-hand anims is not quite correctly, that's how werewolf creature do it and it works correctly (and sky_wereboar_olct.nif also does that). Will push fix soon.

**Comment by Alyst3r** [comment]
Got confirmation from Worsas that he indeed modified kf file for wereboar/werewolf (so, I was incorrect here, but fix will be pushed regardless).
