### ISSUE TITLE
From Bugtracker: tr_dres_bug_small_vo.nif, tr_swampfly_vo.nif

### ISSUE THREAD

**Issue by Dillonn241** [TD-Addon/TD_Addon#205]
Submitted by [abot](https://www.tamriel-rebuilt.org/users/abot) on Tue, 2016-09-13 03:31

**Description:** 

tr_dres_bug_small_vo.nif bounding box should be smaller/resized.

tr_swampfly_vo.nif tends to disappear under the Bal Oyra fort floor, making impossible to kill it and finish the related quest (e.g. if paralyzed, this happens every time if a MCA guard is near) .
Possible things I’d try is changing the Bounding Box to be more similar to the one used e.g. with CliffRacer.nif, covering the flying creature legs and a little below. and/or put some collision box under the fort floor

**Comment by antonisauren** [comment]
I never noticed problems with Muskfly collision myself and those of cliffracers are terrible for ranged characters.
