### ISSUE TITLE
From Bugtracker: Steel Scimitar's texture is of terrible quality

### ISSUE THREAD

**Issue by Dillonn241** [TD-Addon/TD_Addon#206]
Submitted by [urm](https://www.tamriel-rebuilt.org/users/urm) on Sun, 2018-02-04 08:18

**Item/Script Reference:**
**Identifier:** t_com_steel_scimitar_01
**Name:** Steel Scimitar

**Description:** 

the texture looks really bad both from first and third person
stats are also quite weird for such a cheap weapon: higher dps than a silver claymore, while also being one-handed
https://imgur.com/a/kUAj7

**Comment by cheflul** [comment]
fixed by anhora recently
