### ISSUE TITLE
From Bugtracker: Orchish Longsword still clipping through hand after all these years

### ISSUE THREAD

**Issue by Dillonn241** [TD-Addon/TD_Addon#209]
Submitted by [Glisp](https://www.tamriel-rebuilt.org/users/glisp) on Mon, 2019-06-10 06:49

**Description:** 

So, I was hoping by now this would get fixed but it looks like it won't unless I report it. I figured it was an obvious issue. Anyway the weapon "Orcish Longsword" has a clipping problem when held. I've enclosed a screenshot of the issue below.

And before anyone asks, it affects vanilla hands too so it's not a Better bodies related bug.

https://www.tamriel-rebuilt.org/sites/default/files/bugscreens/Morrowind%202019-06-10%2009.41.22.715.jpg

**Comment by revenorror** [comment]
The Orcish weapon set was remade so this model was replaced
