### ISSUE TITLE
From Bugtracker: tr_ex_imp_bdoorg_zy.nif & tr_ex_imp_bdoord_zy.nif

### ISSUE THREAD

**Issue by Dillonn241** [TD-Addon/TD_Addon#210]
Submitted by [Mwgek](https://www.tamriel-rebuilt.org/users/mwgek) on Wed, 2019-09-04 12:49

**Item/Script Reference:**
**Identifier:** T_Imp_SetMw_DoorDoubleOrn_01
**Name:** tr_ex_imp_bdoorg_zy

**Description:** 

Door has bad uv-mapping. It leaves the metal part with a smooth grey reflecting colour. It also has way to many triangles. About 12,000.

https://www.tamriel-rebuilt.org/sites/default/files/bugscreens/door.JPG

**Comment by revenorror** [comment]
This model has actually already been replaced (new ones are tr_ex_om_turjul_door1.nif and 2)
