### ISSUE TITLE
Remove T_Glb_GetTeleportingDisabled

### ISSUE THREAD

**Issue by WoutLamers** [TD-Addon/TD_Addon#212]
Is a duplicate of T_Glob_GetTeleportingDisabled, and this is causing issues where currently in TR_Mainland scripts use T_Glb and dialogue uses T_Glob. Clearly we need to commit to using one or the other, and T_Glob at least follows the proper naming convention.

**Comment by Assumeru** [comment]
https://github.com/TD-Addon/TamrielDataMain/commit/8fc4eaefb4e29330f6cba9340c0b43ca318caf3b
