### ISSUE TITLE
Navy cutter ship sails are bugged

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#215]
The navy variant cutter ship is using blank sails, and seems to have gaps in the sails where it shouldn't. The normal full-sail cutter seems to be fine.

**Comment by revenorror** [comment]
Could you post the file name/ID?

**Comment by Taniquetil24** [comment]
T_Imp_SetHarbor_Cutter_Navy_01 is the one with the sail bugs
