### ISSUE TITLE
Sound Gens missing or with wrong sounds

### ISSUE THREAD

**Issue by hemaris-tr** [TD-Addon/TD_Addon#220]
- [ ] T_Dae_Cre_**AtroStMw_02** — change **Scream** to T_SndCrea_**StormTyrantScream**
- [ ] T_Dae_Cre_**Guardian_01** — ADD **Moan** using T_SndCrea_**GuardianMoan**
- [ ] T_Dae_Cre_**Verm_01** — ADD **Moan** using T_SndCrea_**VermaiMoan**
- [ ] T_Glb_Fau_**BirdChiRs_01** — ADD **Scream** using T_SndCrea_**ChickenScream**
- [ ] T_Glb_Fau_**BirdSeag_01** — ADD **Left** and **Right** using T_SndCrea_**SeagullFlap**

**Comment by cheflul** [comment]
Fixed all but the atronach scream which does not exist
