### ISSUE TITLE
Javelins are overpowered

### ISSUE THREAD

**Issue by cheflul** [TD-Addon/TD_Addon#225]
![TES_Construction_Set_8zDIraCQWV](https://user-images.githubusercontent.com/62924477/170907546-85eb2556-2b6b-4b2e-a619-7521f1d11578.png)
Being the strongest throwing weapon makes sense, they are big and slow, but this is insane

**Comment by RakanishuPT** [comment]
I think the weight of each javelin helps to balance it out since they weigh at least 10x more than the other throwables.  Ex: holding just 10 javelins would equal 70 lbs.

**Comment by cheflul** [comment]
That's fair, though I still don't think the weakest javelin should beat the strongest dart

**Comment by Assumeru** [comment]
I figured the issue was going to be about how that iron damage does more damage than a daedric longsword.
