### ISSUE TITLE
PT (Cyrodiil and Skyrim) in data uses a different DB ranking system than the basegame

### ISSUE THREAD

**Issue by W-E-R-D-N-A** [TD-Addon/TD_Addon#228]
Basegame (Tribunal) uses Daggerfall's ranks for the Dark Brotherhood while for some reason the Skyrim and Cyrodiil chapters use Emil's Oblivion ranking system

**Comment by BlueshiftTR** [comment]
Fixed with https://www.tamriel-rebuilt.org/asset/td-edits-bugs
