### ISSUE TITLE
T_Mw_FloraOW_TreeRedLeaf_** seam

### ISSUE THREAD

**Issue by Assumeru** [TD-Addon/TD_Addon#238]
https://www.tamriel-rebuilt.org/bugtracker/tmwfloraowtreeredleaf-seam

> These trees have a seam running up the stem model, shown here:

![seam](https://www.tamriel-rebuilt.org/sites/default/files/bugscreens/test.png)

**Comment by Snailsting** [comment]
This is still the case for all of these trees except for 02 (at least in SD data)

The geometry is fine, but the UVs on the trunks extend to the transparent part of the texture atlas
![RedLeaf](https://github.com/TD-Addon/TD_Addon/assets/120365872/43a665cf-92d1-494c-a23f-526c873e19a1)

**Comment by Kynesifnar** [comment]
That would explain it

**Comment by Kynesifnar** [comment]
This should be fixed in the commit for the redleaf trees. I assume that this issue only affected the trees when SD textures were being used because the interpolation from HD to SD messed with the alpha layer on the edges of the trunk.
