### ISSUE TITLE
T_De_Furn_Target_01 and T_De_Furn_Target_02 rename

### ISSUE THREAD

**Issue by christixn182** [TD-Addon/TD_Addon#253]
T_De_Furn_Target_01 and T_De_Furn_Target_02 should be renamed to T_Com_Furn_Target_01 and T_Com_Furn_Target_02 respectively. They do not distinctively look Dark Elven and could be used in conjunction with other asset sets. The "De" prefix may discourage devs working on other sets from using these assets in appropriate areas.

**Comment by cheflul** [comment]
reminder to also add this to the translation.txt
