### ISSUE TITLE
tr/i/tr_in_v_s_t_ent_01 - tr/i/tr_in_v_s_t_ent_06

### ISSUE THREAD

**Issue by Tapetenklaus** [TD-Addon/TD_Addon#254]
All these object have collision errors or are missing collision entirely.

**Comment by Alyst3r** [comment]
Quick look in NifSkope, seems like 04 has inverted faces of its collision NiTriShapes. Rest seems ok (although I will probably rework collision shapes a bit to include ledges that may seem missing collisions atm). Pushing fix.
