### ISSUE TITLE
Models using tx_metal_iron_rusty01.dds need to be updated

### ISSUE THREAD

**Issue by Assumeru** [TD-Addon/TD_Addon#257]
`tx_metal_iron_rusty01.dds` has been renamed to `pc_metal_iron_rusty01.dds`.

At the very least this affects `sky_Misc_Hammer_01.nif` and `Sky_Misc_Nails_02.nif`.

**Comment by revenorror** [comment]
So, I gave this a look. Vanilla has textures named Tx_metal_iron_rusty.dds and Tx_metal_iron_rusty_01.dds, but the pc texture is tx_metal_iron_rusty01.dds (note the underscores), so there isn't actually a name overlap. So while the name is unideal we should actually be ok to keep this until the PC textures folder is restructured just to avoid having to go through and fix the meshes
