### ISSUE TITLE
Several data paintings do not correspond with their placement in the CS in game

### ISSUE THREAD

**Issue by christixn182** [TD-Addon/TD_Addon#262]
For several paintings, where they are placed in the CS is different than where they appear in game. It makes paintings placed correctly in game off position or bleeding into nearby wall decorations. It requires carefully positioning them off-position in the CS to get them to their ideal position in game. Could we look over and see what the problems here is? Take a look at the Guild of Painters in Anvil to get an idea of this problem.

**Comment by antonisauren** [comment]
How would such thing be even possible? Isn't it messy linking between multiple installs on @christixn182 part?
