### ISSUE TITLE
T_Imp_SetHarbor_GalleonInUp_02 does not fit T_Imp_SetHarbor_Galleon_01

### ISSUE THREAD

**Issue by Aveno2** [TD-Addon/TD_Addon#273]
As in pictures:
1) Rear raised ceiling does not match.
2) Mizzen mast does not match.
Side issue: 
to match inner upper trapdoor to exterior trapdoor of TR_Narsis_80, the inner upper trapdoor bleeds with the ceiling posts.
![2022_10_21_21_34_50_Window](https://user-images.githubusercontent.com/116307082/197581887-72e0cb16-3675-473c-9d68-9f4a198cbe28.png)
![unknown](https://user-images.githubusercontent.com/116307082/197581964-34fe170f-f9fa-4d79-897f-e49f1b66987e.jpg)

**Comment by Snailsting** [comment]
I think it's pretty safe to say this one can be closed, considering it's about the old galleon models
