### ISSUE TITLE
T_De_FurnP_Chair_01 uses the same vanilla model as furn_de_p_chair_02

### ISSUE THREAD

**Issue by DarkKnightComes** [TD-Addon/TD_Addon#275]
CS entry of T_De_FurnP_Chair_01 links to the same mesh as furn_de_p_chair_02 (but located in the `l` folder for some odd reason), which is furn_de_chair_02.nif
![obraz](https://user-images.githubusercontent.com/16616869/199821474-29c713d8-f93a-4bda-a951-a59323368e82.png)
(vanilla on the left, T_D on the right)

**Comment by cheflul** [comment]
deprecated and added to translation
