### ISSUE TITLE
Missing minotaur textures

### ISSUE THREAD

**Issue by cheflul** [TD-Addon/TD_Addon#278]
[WARN] File not found: [CREA] "T_Cyr_Cre_Mino_01" -> "Data Files\\textures\\pc_minotaura_01.dds"
[WARN] File not found: [CREA] "T_Cyr_Cre_Mino_02" -> "Data Files\\textures\\pc_minotaurb_01.dds"
I can't locate these.

**Comment by Kynesifnar** [comment]
Fixed in 729f178
