### ISSUE TITLE
Minor error in Bellman scripts

### ISSUE THREAD

**Issue by WoutLamers** [TD-Addon/TD_Addon#283]
in T_ScNews_Bellman_Add:
On line 14, change StopScript T_ScNews_Bellman_Lvlist_Remove to StopScript T_ScNews_Bellman_Add
As of right now this does not cause any trouble in TR_Mainland but it's a sloppy typo on my part that should be corrected.

**Comment by Kynesifnar** [comment]
Fixed in https://www.tamriel-rebuilt.org/asset/various-tamriel-data-fixes
