### ISSUE TITLE
Missing Dialogue Topic Info After Tamriel_Data update

### ISSUE THREAD

**Issue by GayusJulius** [TD-Addon/TD_Addon#289]
Hi all! I downloaded the latest Tamriel_Data after it was updated on the 20th and I'm running into an issue that's not letting me start the game. Once the TR Mainland, Skyrim, and Cyrodiil esps attempt to load I am bombarded with several errors relating to missing dialogue topics. 

One example is { "T_Mw_Scribe" not found for dialogue type topic Info "EMPTY" } I receive dozens of these errors related to dialogue that block me from loading up Morrowind. I'm assuming I did something very wrong updating the files, is there anything I can do to fix it? Any help would be appreciated!

**Comment by Assumeru** [comment]
Various things like that class were removed from Data. Mods reliant on older version of Data can fail to load because of that.
