### ISSUE TITLE
Red Mountain error

### ISSUE THREAD

**Issue by PaulusZerth** [TD-Addon/TD_Addon#300]
![Red Mountain error](https://user-images.githubusercontent.com/119131424/204104453-a6ef874b-22c3-4767-8c65-1aadf4a0ddb7.JPG)
So, it's strange...

**Comment by Assumeru** [comment]
Not a Tamriel Data issue.

Your probably load order is probably incorrect. Loading TR before vanilla seems most likely.

**Comment by PaulusZerth** [comment]
![Order](https://user-images.githubusercontent.com/119131424/204104966-a222c28e-5f17-462d-a46d-522ac2c99a7e.JPG)
Well, this is the order)
