### ISSUE TITLE
Typo in an Ebonheart Bellman entry "t_news_bellman_35"

### ISSUE THREAD

**Issue by sultan-of-rum** [TD-Addon/TD_Addon#303]
I seem to have made a typo in one of the Ebonheart Bellman entries that I wrote that hasn't been caught yet. It's in "IMPERIAL TREASURES STOLEN!", with ID t_news_bellman_35. Namely, there is a 'to' missing from '...rumored __ have been traitors...". See the screenshot below.

![screenshot767-marked](https://user-images.githubusercontent.com/87770191/204158168-201822c9-d3b6-485b-8692-99fc161ab081.jpg)

**Comment by Kynesifnar** [comment]
Fixed in https://www.tamriel-rebuilt.org/asset/various-tamriel-data-fixes
