### ISSUE TITLE
Colovian iron/steel armors depreciated 

### ISSUE THREAD

**Issue by Cutmine** [TD-Addon/TD_Addon#305]
"T_imp_coliron1_cuirass_01" etc. All depreciated red boxes in stirk Smith and repair shop.

**Comment by hemaris-tr** [comment]
Thank you for the report. This is a bug with Province: Cyrodiil, not with Tamriel_Data. And P:C hasn't been updated for compatibility with Tamriel_Data 9 yet, so things like this are expected. The update will be out soon.
