### ISSUE TITLE
The Gold Tantha has some gaps in and around its beak

### ISSUE THREAD

**Issue by Snailsting** [TD-Addon/TD_Addon#326]
The Gold Tantha (pc\cr\pc_tantha.nif) (CS ID:T_Cyr_Fau_Tantha_01) has some seams where the beak meets its head, and the roof of its mouth is lacking faces

[Screenshot](https://i.imgur.com/WG9HyFU.png)

EDIT: Additionally, the backsides of their ears seem to be lacking faces as well

**Comment by antonisauren** [comment]
Beak-head looks fine, besides beak opening cutting into base of upper beak base. Backfaces of beak are there but with terrible uvs. Ears still have holes and overall creature is full of texture seams that might be possible to mask a bit.
