### ISSUE TITLE
SH Cave set needed room pieces

### ISSUE THREAD

**Issue by MinerMan60101** [TD-Addon/TD_Addon#327]
The SH Cave room pieces interact with the hall pieces much like the Hlaalu set does, so there are a few parts which would let you build more interesting rooms:

![SH_Cave_Pieces](https://user-images.githubusercontent.com/72769878/210660168-b6ab7b43-d7cb-4cd5-9c61-3d0291341b0a.png)

**Comment by antonisauren** [comment]
From the left: tr_in_shcave_r_sid_02.nif, tr_in_shcave_r_cor_03.nif, tr_in_shcave_r_ent_01.nif, tr_in_shcave_r_sid_03.nif
All are merged to data addon already.
