### ISSUE TITLE
Tamriel Data HD v.9.0 + Hotfix 9 - cannot load meshes

### ISSUE THREAD

**Issue by Dredd893** [TD-Addon/TD_Addon#331]
You can see the errors here: https://imgur.com/a/vh8j9g0

Was trying to play to no avail Vivec Lighthouse (https://www.nexusmods.com/morrowind/mods/52019) together with the quest mod (https://www.nexusmods.com/morrowind/mods/52120)

Cheers

**Comment by Kynesifnar** [comment]
Cannot reproduce; meshes and IDs work fine with latest version.
