### ISSUE TITLE
T_IngFlor_Lavender_01 needs a new model

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#335]
The ingredient model for T_IngFlor_Lavender_01 is enormous and cannot lie flat. It makes it borderline impossible to place on a surface (in alchemy labs, etc)

**Comment by antonisauren** [comment]
It is one to one taken from container plant. Two alpha planes with terrible res texture. To be fair, both should be redone. As quick edit cutting branch in half, scaling it down twice, and stacking more branches as ing object to look more like bouquet could work.
