### ISSUE TITLE
T_De_SetVeloth_I_Ashpit_01 ash bleeds with ground when placed flat 

### ISSUE THREAD

**Issue by Aveno2** [TD-Addon/TD_Addon#347]
![image](https://user-images.githubusercontent.com/116307082/218305035-5d61156c-5cca-46de-b65f-7c151931e11d.png)

**Comment by Snailsting** [comment]
The OAAB version has already been fixed so we should prolly nab that one https://github.com/OAAB-Modding/Data/blob/master/00%20Core/meshes/oaab/i/v_ashpit_tri.nif

**Comment by Snailsting** [comment]
It's just a minor nitpick, but it would be nice if the ash could be made to not spill onto the trim, like in the OAAB version
~~Or alternatively you could still just grab that one~~

![Ashpit](https://github.com/user-attachments/assets/ac294d08-5c6b-4ca4-9e3a-fc1f8e26a897)
