### ISSUE TITLE
Spells added automatically.

### ISSUE THREAD

**Issue by Dredd893** [TD-Addon/TD_Addon#358]
Summon Devourer and Summon Dremora Archer gets added to the spell list automatically
 
 Fix: Open Data Files/MWSE/mods/TamrielRebuilt/main.lua and delete the two tes3.addSpell lines near the bottom

**Comment by Assumeru** [comment]
https://github.com/TD-Addon/TamrielDataMain/commit/fe873416fee8d322855a42c32dea263593d25508
