### ISSUE TITLE
T_Imp_Furn_SpinningWheel_01 needs work

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#365]
The UV is very messy, the front foot block is connected only by a single edge, and the model generally looks very blocky.

Also, the texture is too rich-looking for most normal contexts. Ideally, it should use M wood textures.

Model is `pc\f\pc_furn_spinwheel`

**Comment by antonisauren** [comment]
I recall new model of it appearing somewhere but it's not merged yet.

**Comment by Snailsting** [comment]
Fremennik redid it yeah https://www.tamriel-rebuilt.org/asset/various-asset-improvements
it should be in the next merge

**Comment by antonisauren** [comment]
https://github.com/TD-Addon/TD_Addon/commit/f429a44008fcaa0424385a66817b82e65084dbca
