### ISSUE TITLE
Missing meshes (Shows up in Andothren)

### ISSUE THREAD

**Issue by mdmallardi** [TD-Addon/TD_Addon#368]
I'm getting the following mesh error when in Andothren:
Failed to load 'meshes\tr\x\tr_ex_hm_r3_w01.nif': Resource 'meshes/tr/x/tr_ex_hm_r3_w01.nif' not found, using marker_error instead

I can confirm that this is not in my TR_Data.BSA, My hotfix files or Addon files.

This manifests as some exclamation markers around the rooftop entrance to the Andothren Wharfside Hideout.

**Comment by cheflul** [comment]
Likely has collision from loose files. These had too similar of a filename to another tile.

**Comment by mdmallardi** [comment]
[magamo@beast ~]$ cd .local/share/openmw/data/
[magamo@beast data]$ find . -iname tr_ex_hm_r3_w01.nif
[magamo@beast data]$

Not finding any loose files in my huge data directory that match that name.

**Comment by cheflul** [comment]
Perhaps you are running an esp that has the T_De_SetHla_X_M_R3_Wall_01 object dirtied from before the filename needed to be changed from the hash collision.

**Comment by mdmallardi** [comment]
Okay, I just doublechecked with a very barebones install.  I can confirm that you're definitely right, this works fine without the rest of my load order.
