### ISSUE TITLE
Dres Book has BlahBlahBlah

### ISSUE THREAD

**Issue by 1John418** [TD-Addon/TD_Addon#369]
T_Bk_BlueBookTR which is the Grey Book of 3E 426 contains temporary text - https://media.discordapp.net/attachments/132891272666021888/1103912852470894643/image.png?width=1179&height=663 about House Dres. This book is already in public releases, so let's remove the BlahBlahBlah text and only keep the [square brackets text].

**Comment by JackimoffWackimoff** [comment]
Replaced with dummy text
