### ISSUE TITLE
Cannot load meshes in Vivec

### ISSUE THREAD

**Issue by Nordberg2** [TD-Addon/TD_Addon#370]
Hy, when i run through Vivec, i get this error

https://i.imgur.com/ZVZd1Jj.png

"Object T_B_Imp_HeadColNorthMalePC_04 (Tamriel_Data.esm)
Model Load Error: Meshes\pc\b\PC_B_Imp_M_Head_11.nif
cannot load file
in Meshes\pc\b\PC_B_Imp_M_Head_11.nif"

It happens every time at the same place. Or should i just try to avoid that area? (Vivec is kinda central, lol)

Here you can see my installed mods in the mod manager.

https://i.imgur.com/5EtumFw.png

Is this a problem with this mod?

Kind regards

**Comment by Snailsting** [comment]
Hey there

This problem seems to be caused by one or more of the BSA files not being properly registered
Please see the FAQ on our site for some more info on what might be causing your issues and what you can do to resolve them https://www.tamriel-rebuilt.org/about/frequently-asked-questions/bsa

Also make sure you're not still loading PT_Data.bsa as it is no longer being supported
We had to spit it up into PC_Data.bsa and Sky_Data.bsa because it became too big

**Comment by Nordberg2** [comment]
I noticed the bsa file updater myself and used the script to update my save files.

I just don't know what else to update. I can't find the mod, which required Tamriel_data in the first place -_- (I dont use Tamriel Rebuilt)

**Comment by Nordberg2** [comment]
> Hey there
> 
> This problem seems to be caused by one or more of the BSA files not being properly registered Please see the FAQ on our site for some more info on what might be causing your issues and what you can do to resolve them https://www.tamriel-rebuilt.org/about/frequently-asked-questions/bsa

Because another mod, not Tamriel Rebuilt, needed the data files, I'm not sure, which files to update with the jar script. The esm and esp files?

**Comment by Nordberg2** [comment]
Is there maybe a list of nexus mods, that require Tamriel_data to install?

Then i might be able to find the mod, that i also need to update, apperently

**Comment by Snailsting** [comment]
The "requirements" drop down window on the description tab of TD's Nexus page  should have a list of all the mods that have TD listed as a dependency on the Nexus

https://i.imgur.com/N9GJywZ.png

**Comment by Nordberg2** [comment]
> The "requirements" drop down window on the description tab of TD's Nexus page should have a list of all the mods that have TD listed as a dependency on the Nexus
> 
> https://i.imgur.com/N9GJywZ.png

Thank you, i think it's this one https://www.nexusmods.com/morrowind/mods/49149

This mod doesn't leave an esm/esp file in data files directory. Which file do i have to update with the translation script?

**Comment by Snailsting** [comment]
I'm not really sure TBH, you're best off just asking about this stuff on the TR Discords troubleshooting channel, there should be a link on the site

**Comment by Nordberg2** [comment]
This issue was resolved in dicord. I had to use the file updater TR_filepatcherv2.jar and edit the Morrowind.ini via the Mod Manager 2, like it was already explained in the documentation. It was my fault and a false issue. I'm sorry for wasting your time and thank everybody who helped me out.

Feel free to delete this issue
