### ISSUE TITLE
T_Nor_Var_WerewolfboneDagger_01 geometry and style problems

### ISSUE THREAD

**Issue by Kynesifnar** [TD-Addon/TD_Addon#390]
The geometry for this weapon's mesh (tr_w_sacr_dagger.nif) is highly unoptimized, consisting of thousands of triangles. Some parts of the blade are also shaped strangely.

To make matters worse, the weapon's aesthetic in general seems very plain and (in my opinion) ill-suited to Morrowind. Changing the texture and making the geometry more interesting would be ideal, assuming that it is worth keeping this weapon at all.

**Comment by Snailsting** [comment]
This one has since been deprecated afaik
