### ISSUE TITLE
Incorrect Texture Size

### ISSUE THREAD

**Issue by jamrt** [TD-Addon/TD_Addon#41]
Reported by Corsair on Nexus.

>  I recently updated my files and I'm still having issues with textures not appearing with the "Ancient Nord Copper Coin" (T_Nor_CoinBarrowCopper_01). The other two variants of the coin appear normally, but "tx_sky_ancientnordcoins_02" won't appear in-game, as seen in the image below. I extracted the texture from the BSA, and noticed it's sized at 256x256, so maybe that's the issue, but I'm not sure. 
![lLT7JFB](https://user-images.githubusercontent.com/57233780/101530277-fb0e6d80-3991-11eb-83aa-6fb553ab5476.jpg)

**Comment by Texafornian** [comment]
I'm pretty sure this is an OpenMW issue.  That copper coin might have a NiTextureEffect node.

**Comment by Corsair83** [comment]
I'm not on using OpenMW, so could the NiTextureEffect still be at fault with vanilla engine/MGEXE?

**Comment by cheflul** [comment]
Specular material settings were wrong, fixed
