### ISSUE TITLE
Book Alterations to Match current TR and Project Tamriel geography.

### ISSUE THREAD

**Issue by W-E-R-D-N-A** [TD-Addon/TD_Addon#416]
T_Bk_FatherOfTheNibenOpenPC/T_Bk_FatherOfTheNibenPC should have the mention of Gorne edited to refer to the current name of TR's Padomaic island (Old Gorne) after Gorne proper was moved to the inner sea. Nan Iban is the settlement name, not sure what or if the island was renamed yet. I will add that info when I have it.

T_Bk_AyleidRuinsPC should have the mention of Gottlesfont Priory (which won't exist in PC) replaced with Delodiil which is in the approximate position. This way the book will give accurate directions to an Ayleid dungeon for the player and put an otherwise decent lorebook in accordance with our lore.

**Comment by JackimoffWackimoff** [comment]
Father of the Niben has already been changed, edited Ayleid Ruins as suggested
