### ISSUE TITLE
The NightDaySwitch - node of pc_ex_gall_unfurled.nif is not a NiSwitchNode

### ISSUE THREAD

**Issue by worsas** [TD-Addon/TD_Addon#417]
**pc_ex_gall_unfurled.nif**
This node needs to be turned into a NiSwitchNode to work properly and may need to be moved above the RootCollisionNode. In my experience the NightDaySwitch - node always needs to be the first child node in the nif tree.

**pc_ex_gall_furled.nif**
Here the NightDaySwitch - node is correctly a NiSwitchNode, but it may need to be moved to the top of the nif tree aswell in order to work, so it is also the first child of the base node.

**Comment by Kynesifnar** [comment]
Probably should have closed this when I merged the fixed versions.
