### ISSUE TITLE
Ynesai lack vampire heads

### ISSUE THREAD

**Issue by Assumeru** [TD-Addon/TD_Addon#418]

**Comment by Kynesifnar** [comment]
Just a heads up for you (and whoever makes these): I made a page for these on the asset browser (https://www.tamriel-rebuilt.org/asset/ynesai-vampire-heads) a few weeks ago.

**Comment by Kynesifnar** [comment]
Fixed by https://www.tamriel-rebuilt.org/asset/addtional-ynesai-heads-vampire-heads
