### ISSUE TITLE
sky_furn_futtertrog2.nif in PT_Data.bsa

### ISSUE THREAD

**Issue by jamrt** [TD-Addon/TD_Addon#42]
Reported by abot on Nexus

>  sky_furn_futtertrog2.nif in PT_Data.bsa points to wrong tx_skyrim_grain_musp.dds, should probably be fixed to tx_skyrim_grain_01.dds or pc_tx_skyrim_grain_01.dds (they are the same I think)

> 
> also these are crashing the CS preview window and I suppose also in game
> f\sky_furn_n_frg_01_02.nif
> f\sky_furn_n_frg_02_01.nif
> f\sky_furn_n_frg_02_02.nif
> f\sky_furn_n_frg_03_01.nif
> f\sky_furn_n_frg_03_02.nif
> f\sky_furn_n_frg_04_01.nif
> 
> [EDIT]I think
> xsky_furn_n_frg_02_01.kf
> xsky_furn_n_frg_03_01.kf
> xsky_furn_n_frg_04_01.kf
> are broken, copying xsky_furn_n_frg_01_01.kf over them seems to fix the crash
> 
> TES3Stream Warning: Model "Meshes\EPoS\b\epos_b_ks_f_head_03.nif" tex not found "textures\epos\epos_tx_b_n_ks_f_h02.dds"!
> Texture Load Error!: textures\epos\epos_tx_b_n_ks_f_h02.dds
> this is probably due to a hash collision between textures\epos\epos_tx_b_n_ks_f_h01.dds and (try to look at CS preview of meshes before releasing!), one of the textures mus be renamed to be able to be packed in the same .bsa

**Comment by cheflul** [comment]
sky_furn_futtertrog2.nif, sky_furn_n_frg_01_02, 04_01, and all the xsky frg are no longer present in the plugin or BSAs, frg 02_01, 02_02, 03_01 and 03_02 all work as statics in game, but do still crash the preview window, so I'm leaving this issue open.
The epos hash collision appears to be fixed but I'll have to check again when testing the packed TD8 BSAs
