### ISSUE TITLE
"ArrowBone missing on actor" error when firing T_De_Chitin_Crossbow

### ISSUE THREAD

**Issue by RonikTR** [TD-Addon/TD_Addon#420]
On vanilla engine, every time the player or any NPC fires the T_De_Chitin_Crossbow and finishes the firing animation, an error appears saying "ArrowBone missing on actor". If you ignore the error, you can continue to play as normal, but it's still very annoying especially when you're in combat with a NPC that is using the weapon.

On OpenMW, the weapon is completely broken - when you try to fire it, the animation plays out as normal, but it never does any damage and no bolts are deducted from your inventory.

**Comment by antonisauren** [comment]
[tr_w_chitin_crossbow.zip](https://github.com/TD-Addon/TD_Addon/files/14998219/tr_w_chitin_crossbow.zip)
Just cut suffixes from bone names. Reavane checked it on both engines and supposedly works perfectly fine.
