### ISSUE TITLE
T_Imp_SetHarbor_GalleonIn_Decks - vertical support doesn't reach lowest deck

### ISSUE THREAD

**Issue by Exovian** [TD-Addon/TD_Addon#421]
Pretty straightforward; the vertical beam supporting the stairs to the lowest deck doesn't reach the floor, and instead floats a few inches above it. It also caspers on the bottom, though I can't imagine how a player would ever see it.

![error1](https://github.com/TD-Addon/TD_Addon/assets/5644295/9eda2b16-7d81-401c-bedc-2f72cdbd20d8)
![error2](https://github.com/TD-Addon/TD_Addon/assets/5644295/9fda93a6-d2b1-4eef-a09e-894892728a87)

**Comment by Kynesifnar** [comment]
Sigh
