### ISSUE TITLE
couple of CaveSH set issues

### ISSUE THREAD

**Issue by Aveno2** [TD-Addon/TD_Addon#428]
T_Mw_CaveSH_Exit_02 ceiling does not connect
![image](https://github.com/TD-Addon/TD_Addon/assets/116307082/554a45f2-9337-4305-b7d8-1a4c2cdc08de)
T_Mw_CaveSH_NS_Room_10 has a casper
![image](https://github.com/TD-Addon/TD_Addon/assets/116307082/c0ecfd12-2c23-41c2-97e6-990a251d6657)

**Comment by antonisauren** [comment]
Fixed in asset pack https://www.tamriel-rebuilt.org/asset/further-additions-and-fixes-shipal-shin-cave-set Could be cherry-picked now but both pieces will probably get collision edits later on.

**Comment by antonisauren** [comment]
Fix merged there https://github.com/TD-Addon/TD_Addon/commit/6e23dbd893d34cb4b3b34fffc19f725575ab849d
