### ISSUE TITLE
T_IngFlor_Bottomweed_01 is only selectable from the underside in the Construction Set

### ISSUE THREAD

**Issue by Aveno2** [TD-Addon/TD_Addon#430]

**Comment by Snailsting** [comment]
This seems to be caused by it being one surface with backface culling disabled instead of two with the normals pointing in opposite directions

**Comment by Snailsting** [comment]
Fix posted to: https://www.tamriel-rebuilt.org/asset/assorted-model-fixes-sep-2024

**Comment by antonisauren** [comment]
https://github.com/TD-Addon/TD_Addon/commit/4eb16e28d320ad72b9c924f966f4dacc641d4f4d
