### ISSUE TITLE
T_Glb_Und_SkelWLor_01 shouldn't use silver levelled list

### ISSUE THREAD

**Issue by Aveno2** [TD-Addon/TD_Addon#434]
T_Glb_Und_SkelWLor_01 is used in ancestral tomb levelled list. the silver weapon levelled list uses imp_ weapons making it inappropriate for dunmer tombs

**Comment by Snailsting** [comment]
The Skeleton Champion used in Vanilla's tomb leveled lists uses silver weapons too
Which aren't treated as Com in TD, we have the TD generic enchanted variants of those vanilla weapons marked as T_Imp as well

So the current implementation doesn't seem inconsistent with Vanilla to me, at least

**Comment by Aveno2** [comment]
True. Vanilla usage overrides this concern.
