### ISSUE TITLE
Missing Object

### ISSUE THREAD

**Issue by dreadnod244** [TD-Addon/TD_Addon#440]
Hello, not sure this will be my ownly issue so I will just refer to this as missing object.

anyways I keep getting this popup error before a crash.

Expression Error Unable to find object 'TR_m2_q_22_FMGEChapel' in script BKU-LibraryGlobal_TR8

**Comment by Assumeru** [comment]
That's not a Tamriel Data issue.

Whichever mod added `BKU-LibraryGlobal_TR8` seems to have been made for an older version of Tamriel Rebuilt than the one you have,
