### ISSUE TITLE
Overpowered Bloodmoon Silver Sword of Paralysis in TR and TData leveled list.

### ISSUE THREAD

**Issue by Donnerino12** [TD-Addon/TD_Addon#445]
Two NPCs in TR in Map 1 and Map 4 have Bloodmoon's Silver Sword of Paralysis which does more damage than Daedric weapons whilst paralyzing. This weapon is also found in the leveled list at PC Level 15. The following ESP will remove those weapons from the data leveled list.

[TD OP Sword Fix.zip](https://github.com/TD-Addon/TD_Addon/files/12487924/TD.OP.Sword.Fix.zip)

**Comment by Assumeru** [comment]
Also removed the Silver Axe of Paralysis from T_Mw_Lvl_WeaponsAxeOneHand.
