### ISSUE TITLE
Dagi-raht race is misnamed

### ISSUE THREAD

**Issue by Kynesifnar** [TD-Addon/TD_Addon#447]
All of the other Khajiit "races" are just named "Khajiit", but the new Dagi-raht race is named "Dagi-raht" instead.

**Comment by Assumeru** [comment]
None of them are named Khajiit at present. They really should be to ensure consistent `%Race` output though.

**Comment by Kynesifnar** [comment]
I suppose that the names must have been one of the mods I have active then, which I erroneously assumed wouldn't change something like that.
