### ISSUE TITLE
Missing collision on static int piece (T_Imp_LegionCyr_I_SpiralTop_01)

### ISSUE THREAD

**Issue by FluxBugzapper** [TD-Addon/TD_Addon#448]
Repost from: https://www.tamriel-rebuilt.org/bugtracker/missing-collision-static-int-piece-timplegioncyrispiraltop01

"The center of the interior piece doesn't have collision, and you can fall right through.

This int piece is part of the Legion set that will be used on both PC and PI."

![Morrowind 2023-09-10 22 55 14 545](https://github.com/TD-Addon/TD_Addon/assets/134028178/d55b4ec1-d942-439b-8297-6551072cec81)

**Comment by Kynesifnar** [comment]
This issue also shows up in the Mw variant of this mesh.
