### ISSUE TITLE
T_Com_UNI_KingOrgnumCoffer_01 doesn't work at all in vanilla

### ISSUE THREAD

**Issue by RonikTR** [TD-Addon/TD_Addon#450]
As title says.

The core of the issue is that the script T_ScObj_KingOrgnumCoffer_01 is trying to initiate a ForceGreeting with a creature that's located in a dummy cell that the player will never enter, so that it looks that the player is talking to the coffer. In OpenMW this works fine, in vanilla it just doesn't do anything.

I haven't found any evidence that there's actually any reliable workaround to make this sort of thing work on the vanilla engine - UESP suggests to PositionCell the creature before you trigger the ForceGreeting, but even when combined with Position to player's coordinates, this simply didn't work at all.

There are also other issues with the coffer and its dialogue, as described in #298.

I've submitted a fix for this and #298 here: https://www.tamriel-rebuilt.org/asset/tdata-king-orgnums-coffer-fix

**Comment by Assumeru** [comment]
c1e539b1d00f8d6a4a5362d21764be07d6db97a3
