### ISSUE TITLE
T_Mw Goblins use Tribunal leveled lists

### ISSUE THREAD

**Issue by RonikTR** [TD-Addon/TD_Addon#452]
As title says. At the moment, TR has to use T_Sky Goblins instead.

I've submitted a fix for this and #354 here: [https://www.tamriel-rebuilt.org/asset/tdata-tmw-and-tcyr-goblin-fixes](https://www.tamriel-rebuilt.org/asset/tdata-tmw-and-tcyr-goblin-fixes)

**Comment by Assumeru** [comment]
8bdf02ebe68938bd5a1f8e3d2b0696168165ba18
