### ISSUE TITLE
T_Nor_Orn_Halberd_01 is translucent in first-person

### ISSUE THREAD

**Issue by boatqueen** [TD-Addon/TD_Addon#457]
As the title says, T_Nor_Orn_Halberd_01 is translucent in first person. Oddly, the only thing that can be seen through the halberd is NPCs and only when you are close to them.

**Comment by Kynesifnar** [comment]
This isn't specific to the Nordic halberd; the same thing happens with other long weapons which are held close to an NPC (such as by holding an attack near them).
