### ISSUE TITLE
(Saint) Seryn signposts no longer needed

### ISSUE THREAD

**Issue by Revane-Crowford** [TD-Addon/TD_Addon#459]
Saint Seryn is called Andrethis now, so the signs need to be changed. Preferably both the display name and the ID, so people can find them.

This affects:

- T_Com_SetMw_SignWaySaintSery_01
- T_Com_SetMw_SignWaySeryn_01

These are redundant anyway, using the same model and are just different in the display name (Seryn vs. Saint Seryn), neither of which is correct.

- T_Com_SetMw_SignWaySaintSery_02

The _02 version.

**Comment by Revane-Crowford** [comment]
I was mistaken, Andrethis signs already exist, so there's not need to change the old Saint Seryn signs. They're just useless now and could be removed, but no rush.

**Comment by JackimoffWackimoff** [comment]
Deprecated
