### ISSUE TITLE
T_Glb_Und_SkelWLor_01 (Skelly warlord) needs to be beefed up compared to T_Glb_Und_SkelCmpGr_01 (greater champion)

### ISSUE THREAD

**Issue by Aveno2** [TD-Addon/TD_Addon#462]
Warlord is higher level, yet has the same health, worse combat stats
![image](https://github.com/TD-Addon/TD_Addon/assets/116307082/c3e7ad0d-cb65-45cf-9cd4-d97574cc311a)

**Comment by JackimoffWackimoff** [comment]
Buffed Warlord's stats to match but further increased health and attack damage max.
