### ISSUE TITLE
Some PT plants are missing textures in TD10

### ISSUE THREAD

**Issue by RonikTR** [TD-Addon/TD_Addon#474]
As title says.

What seems to have happened is that these plants were supposed to have their meshes and textures replaced with atlased variants ([5eee49c](https://github.com/TD-Addon/TD_Addon/commit/3ddb1e5f2795a68ee85236bc4d4804b1b015f60c)), but only some of the replacements were commited (3ddb1e5).

As far as I can see, we need to add these textures back to T_D. There's possibly more issues, but these are the ones I was able to find so far.

textures\pc_flora_milkthistle_01.dds
textures\pc_flora_milkthistle_02.dds
textures\pc_flora_milkthistle_03.dds
textures\pc_flora_milkthistle_04.dds
pc_flora_sjw_flower.dds
textures\tx_skyrim_kthistle_01.dds
textures\tx_skyrim_kthistle_02.dds
textures\tx_skyrim_kthistle_03.dds
textures\tx_skyrim_kthistle_04.dds
textures\tx_skyrim_rose_01.dds

**Comment by JackimoffWackimoff** [comment]
fixd
