### ISSUE TITLE
The texel density on the rock part of tr\i\tr_in_shcave_room_10.nif is insanely low

### ISSUE THREAD

**Issue by Snailsting** [TD-Addon/TD_Addon#485]
![Room 10](https://github.com/TD-Addon/TD_Addon/assets/120365872/785fe008-7e1b-4966-91a0-29f1459369e3)
(I think that's the correct term at least?)

**Comment by antonisauren** [comment]
Corridor sets standard to 382px/100u. All cave pieces were off by various margin.

**Comment by antonisauren** [comment]
Cave rooms got unified texel density here Should be fixed in https://www.tamriel-rebuilt.org/sites/default/files/assets/Shipal-Shin%20cave%20set_5.7z
