### ISSUE TITLE
change weather for sunny PC regions

### ISSUE THREAD

**Issue by roerichPT** [TD-Addon/TD_Addon#487]
IMO the region weather for the Gold Coast regions (Abecean, Brennan Bluffs etc.) is still too dour. Here's my proposals:

Gold Coast
Clear: 70
Cloudy: 20
Foggy: 0
Overcast: 0
Rain: 5
Thunder: 5

Abecean Sea:
Clear: 80
Cloudy: 10
Foggy: 5
Overcast: 0
Rain: 0
Thunder: 5

Gilded Hills/Brennan Bluffs looks alright

- Roerich

**Comment by TriWubbly** [comment]
[AS_WeatherFix.esp.zip](https://github.com/user-attachments/files/18017187/AS_WeatherFix.esp.zip)
