### ISSUE TITLE
T_Mw_CaveSH_Curve_04 seams 

### ISSUE THREAD

**Issue by Aveno2** [TD-Addon/TD_Addon#503]
![image](https://github.com/TD-Addon/TD_Addon/assets/116307082/e2103093-fa0f-45c3-98b8-bc13ffcec5e7)
![image](https://github.com/TD-Addon/TD_Addon/assets/116307082/9df82571-5c6f-4070-b6bf-0ec0d374ec14)

**Comment by Aveno2** [comment]
![image](https://github.com/TD-Addon/TD_Addon/assets/116307082/1daa3720-6d6f-48e1-a025-fa1c62f4195c)

**Comment by antonisauren** [comment]
Fixes to T_Mw_CaveSH_Curve_04 [tr_in_shcave_curve_04.zip](https://github.com/TD-Addon/TD_Addon/files/13605202/tr_in_shcave_curve_04.zip)

**Comment by antonisauren** [comment]
All room pieces and adjected side walls are asymetrical. They require larger rework.

**Comment by Aveno2** [comment]
T_Mw_CaveSH_Ramp_01 too steep to ascend when setscale 2

**Comment by Aveno2** [comment]
![image](https://github.com/TD-Addon/TD_Addon/assets/116307082/90244794-ce95-46af-b799-b56bbec3af42)
T_Mw_CaveSH_HallSToHallL_02 seam

**Comment by antonisauren** [comment]
Fix for that large intersection and steep ramps: [shcave.zip](https://github.com/TD-Addon/TD_Addon/files/13622328/shcave.zip)

**Comment by Kynesifnar** [comment]
Just to let you know in case you didn't Stele: You are free to merge these into TD_Addon yourself. Preferably with GitHub Desktop.
