### ISSUE TITLE
T_Mw_CaveSH_R_Cor_03 & T_Mw_CaveSH_NS_R_Ent_01 casper / don't fit

### ISSUE THREAD

**Issue by shadowhawk-the19th** [TD-Addon/TD_Addon#505]
These two pieces don't seem to fit properly.

T_Mw_CaveSH_R_Cor_03 - roof caspers

![CaveSHbug1](https://github.com/TD-Addon/TD_Addon/assets/66216972/d60e6e64-c15f-43d6-ac61-c105a59286dc)

T_Mw_CaveSH_NS_R_Ent_01 - floor caspers

![CaveSHbug2](https://github.com/TD-Addon/TD_Addon/assets/66216972/89e2dd8f-23b9-4a72-9890-9355fe0f6168)

**Comment by shadowhawk-the19th** [comment]
Disregard "T_Mw_CaveSH_NS_R_Ent_01" - this one is already fixed.

**Comment by antonisauren** [comment]
Fix for the first one: [tr_in_shcave_r_cor_03.zip](https://github.com/TD-Addon/TD_Addon/files/13624927/tr_in_shcave_r_cor_03.zip)
