### ISSUE TITLE
Colovian barrow set gaps

### ISSUE THREAD

**Issue by Snailsting** [TD-Addon/TD_Addon#506]
The Colovian barrow set has some gaps that aren't the most pressing issue, but would be good to have fixed before Anvil comes out

pc/i/pc_in_col_barrstr1.nif (T_Imp_DngColBarrow_I_Stair_01) Has a small hole above one of the topmost steps, and two of them next to each other won't line up properly
![cb stairfloorgap](https://github.com/TD-Addon/TD_Addon/assets/120365872/d83408e5-b5b4-4da0-b609-f61aa9c0ebcd)

pc/i/pc_in_col_barrceil4.nif (T_Imp_DngColBarrow_I_Ceil_04) The rounded corners on the dirt part mean it'll leave a hole when snapped to the other ceiling pieces
and on top of that, one of its sides doesn't line up with the other ceiling pieces
![Cb Ceil4](https://github.com/TD-Addon/TD_Addon/assets/120365872/21be97a0-9166-455f-bdf1-09b442ffdec2)

pc/i/pc_in_col_barrwal11.nif (T_Imp_DngColBarrow_I_Wall_11) Has small gap underneath the topmost shelf
![cb Wall11](https://github.com/TD-Addon/TD_Addon/assets/120365872/3b74b20f-272d-44e0-8750-f4f7a68458fd)

pc/i/pc_in_col_barrwal9.nif (T_Imp_DngColBarrow_I_Wall_09) Has two small holes
![CB Wall09](https://github.com/TD-Addon/TD_Addon/assets/120365872/3db5ef76-7ae4-40fd-a6e6-89caaf418284)

pc/i/pc_in_col_barrpas5.nif (T_Imp_DngColBarrow_I_Passtairs) has a hole in its ceiling
![Cb passstairceil](https://github.com/TD-Addon/TD_Addon/assets/120365872/c27d041d-3099-481a-a119-8a8fa43fcbb8)

And there's the matter of the passage pieces being about 0.25 units to long or short at the connecting edges, which causes them to either have a gap or slightly Z-fight depending on how they're used

Disregard the screenshot, they're actually all slightly fucked I just made that before I took their measurements in Blender
![CB Passstair](https://github.com/TD-Addon/TD_Addon/assets/120365872/5341af33-0d57-45f6-b181-23e0e426fe79)

**Comment by antonisauren** [comment]
pc_in_col_barrpas5.nif and pc_in_col_barrstairs02.nif are the same mesh. Something is messed up in there.
