### ISSUE TITLE
Colovian Battlewine has Damage Intelligence instead of Drain

### ISSUE THREAD

**Issue by FeuerTiger86** [TD-Addon/TD_Addon#513]
Many Alcohols have a "Drain Intelligence" Effect on them that lowers the attribute for a certain time by a certain number before it returns to normal. However, the Colovian Battlewine (T_Imp_Drink_WineBattle_01) has "Damage Intelligence" instead. This means, instead of lowering Int by 30 for 30 seconds, drinking it damages Int by 30 per second for 30 seconds, for a total of 900, which most likely reduces the attrbute to 0. I'm sure this is not intended and the "Drain" Effect should be used instead.

**Comment by Assumeru** [comment]
Duplicates #499.
