### ISSUE TITLE
The UVs on the Steel Scimitar's blade are borked

### ISSUE THREAD

**Issue by Snailsting** [TD-Addon/TD_Addon#520]
tr\w\tr_w_steel_scimitar.nif
![Scimmi](https://github.com/TD-Addon/TD_Addon/assets/120365872/dd74560a-1582-42cb-9bee-dbcb82fcae1f)

**Comment by Kynesifnar** [comment]
Fixed in https://github.com/TD-Addon/TD_Addon/commit/b4ab407bc90cc67b40c6f29f00bd47cab280c7f8
