### ISSUE TITLE
Please update rank names for Itinerant Priests faction

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#532]
Ranks should be revised to
0 - Layman
1 - Novice
2 - Gyrovague
3 - Robe-Bearer
4 - Seeker
5 - Disciple
6 - Mendicant
7 - Elder
8 - Marabout
9 - Wayfarer

**Comment by cheflul** [comment]
Ronik did this here https://www.tamriel-rebuilt.org/asset/tdata-various-fixes-jan-24 but please just make an esp instead of an issue next time
