### ISSUE TITLE
PC guard changes

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#540]
All of the following should become rank Auxiliary of the T_Cyr_KingdomAnvil faction
- PC_Guard_GC
- PC_Guard_GC_02
- PC_Guard_GC_f
- PC_Guard_GC_f_02

All of the following should be deprecated
- PC_Guard_Str
- PC_Guard_Str_f
- PC_Guard_Str_wander

All of the following should become rank Auxiliary of the T_Cyr_KingdomSutch faction
- PC_Guard_Sut
- PC_Guard_Sut_f
- PC_Guard_Sut_wander

The Sutch guards will eventually also need armor replacements, but the armor has not yet been made.

**Comment by Assumeru** [comment]
Superseded by #547.
