### ISSUE TITLE
T_Ham_TerrRockGM_RockCliff_01/02/03 texture is missing

### ISSUE THREAD

**Issue by RonikTR** [TD-Addon/TD_Addon#541]
As title says. The texture path is pointing to a texture in **textures\hf\lnd\ph_tx_gm_rockcliff_01.dds** which doesn't exist. It's probably supposed to use **ph_tx_gm_rock_01.dds** instead.

**Comment by JackimoffWackimoff** [comment]
textures\hf\lnd\ph_tx_gm_rockcliff_01.dds does now exist
