### ISSUE TITLE
PC book icon has black background

### ISSUE THREAD

**Issue by MinerMan60101** [TD-Addon/TD_Addon#55]
Icons/pc/m/pc_bk_book_38.tga has a black background instead of a transparent background

**Comment by antonisauren** [comment]
Yup, every single one.

**Comment by hemaris-tr** [comment]
@antonisauren did you fix this recently?

**Comment by antonisauren** [comment]
https://github.com/TD-Addon/TD_Addon/commit/a23711a07e44bd977d31fbcb51d4c95cae1275fc
