### ISSUE TITLE
Broken bottle missing ID after properly installing Tamriel Data and TD Graveyard

### ISSUE THREAD

**Issue by antiochean** [TD-Addon/TD_Addon#553]
Hi everyone. I don't know how to solve this issue: from the 23.10 version I keep receiving the error message that there's a missing ID of Misc static  "broken bottle_04". What can I do? I've also patched the latest Tamriel data.esm version with FilePatcher but nothing changed.

**Comment by Assumeru** [comment]
You're not supposed to patch Tamriel Data. Regardless, that doesn't look like one of our IDs. Also this tracker isn't a good place to get support.
