### ISSUE TITLE
rock-columns-are-scaled-incorrectly

### ISSUE THREAD

**Issue by Bicklesboi** [TD-Addon/TD_Addon#559]
T_Pi_TerrRockCQ_RockNestColumn

T_PI_TerrRockYN_RockNestColumn

Are at a huge scale.

**Comment by Snailsting** [comment]
Was fixed in https://github.com/TD-Addon/TD_Addon/commit/342cf63145464b26ae0bd5a4c33f1d5606917290 (https://www.tamriel-rebuilt.org/asset/pi-various-mesh-fixes)
