### ISSUE TITLE
tpiterrrockpocaveentr04-should-be-marked-cq-instead-po

### ISSUE THREAD

**Issue by Bicklesboi** [TD-Addon/TD_Addon#560]
T_Pi_TerrRockPO_CaveEntr_04 should use the PO rock texture but instead uses the CQ texture.

**Comment by antonisauren** [comment]
Shoud they be renamed or texture swapped?

**Comment by RonikTR** [comment]
This appears to have been fixed in 342cf63145464b26ae0bd5a4c33f1d5606917290
