### ISSUE TITLE
Dreugh beads shouldn't block player movement

### ISSUE THREAD

**Issue by 1John418** [TD-Addon/TD_Addon#561]
The [following statics](https://media.discordapp.net/attachments/800812964658675783/1202713952023478354/image.png?ex=65ce75a7&is=65bc00a7&hm=0bcabc89e7d3ac5ae58726e97018bee76afac6031ef01786c92ab20818a12767&=&format=webp&quality=lossless&width=844&height=663) don't need collision, the player should be able to move through:

- T_Dreu_Furn_Beads_01
- T_Dreu_Furn_Beads_02
- T_Dreu_Furn_Beads_03
- T_Dreu_Furn_Tapestry_02
- T_Dreu_Furn_Tapestry_03
- T_Dreu_Furn_Tapestry_04
- T_Dreu_Furn_Tapestry_05

**Comment by Exovian** [comment]
Not actually completed; T_Dreu_Furn_Tapestry_04 (tr_furn_dreu_tapest_04.nif) still blocks player movement in current TD.
