### ISSUE TITLE
Nirnroot plant not correctly displaying in-game and in the CS

### ISSUE THREAD

**Issue by Snailsting** [TD-Addon/TD_Addon#563]
pc\o\pc_flora_nirnroot.nif
It looks fine if Nifscope, but for some reason leaves seem to be in the wrong position and the lower part of the plant doesn't display at all in-game

![MemePlant](https://github.com/TD-Addon/TD_Addon/assets/120365872/57d44a0b-1f2d-447b-b4d0-3deec0a524b2)

**Comment by Kynesifnar** [comment]
Fixed by https://github.com/TD-Addon/TamrielDataMain/commit/5e44e40ef1e92d29ea6a71694f195959c14e15c6

One of the stranger issues that I think I've seen.
