### ISSUE TITLE
T_Cyr_TerrSandGC_Heap_02 stretched texture

### ISSUE THREAD

**Issue by Aveno2** [TD-Addon/TD_Addon#575]
![image](https://github.com/TD-Addon/TD_Addon/assets/116307082/5f486fc4-03fe-432f-8aba-24eb0d663339)

**Comment by shtou23** [comment]
[pc_terrain_sand_02.zip](https://github.com/TD-Addon/TD_Addon/files/14917981/pc_terrain_sand_02.zip)
Re-unwrapped-ed the object, tris>quads+angle based unwrapped. Looks good to me.
