### ISSUE TITLE
T_De_FurnP_HlaSewerAlcShelf01 has a bunch of small gaps

### ISSUE THREAD

**Issue by Snailsting** [TD-Addon/TD_Addon#577]
tr\f\tr_furn_de_p_alc_shelf.nif
![shelf1](https://github.com/TD-Addon/TD_Addon/assets/120365872/d743cb4d-91fc-40df-97d7-2733a46189c9)
![shelf2](https://github.com/TD-Addon/TD_Addon/assets/120365872/df222f7a-8fdd-4e10-abee-8875ed6eab2e)

**Comment by shtou23** [comment]
[Issue_577_fix.zip](https://github.com/TD-Addon/TD_Addon/files/14749487/Issue_577_fix.zip)
Fixed seams in screenshots
![shelf_fixed_no_seam](https://github.com/TD-Addon/TD_Addon/assets/157419616/515a1910-40d2-4dcb-a175-0f2a0af27949)
