### ISSUE TITLE
Colovian Lamellar pauldrons tex error

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#578]
TES3Stream Warning: Model "Meshes\a\pc_a_westerner_pldron_gnd.nif" tex not found "e: morrowind_models\westerner_armor\pauldron\pc_a_westerner_armor.png"!

Looks like there's a bad texture path in the pauldrons when they are placed in the world. Works fine when equipped on an NPC - maybe just pulling from a different source.

**Comment by Taniquetil24** [comment]
Actually it looks like it's a model path issue - the textures are fine on the correct models, but the armor IDs point to the wrong place

**Comment by antonisauren** [comment]
I don't see pc_a_westerner armor in TD at all.
