### ISSUE TITLE
Can't run the mod "mournhold" issue

### ISSUE THREAD

**Issue by Zatoishi1** [TD-Addon/TD_Addon#582]
The game is telling me in a first window
"Expresssion Error Unable to find dialogue topic/journal "alit hide" in script T_ScGlobal_AddAnimalProdTopsTR"
Then in a second
"Expression Error Unable to find cell id "Mournhold" in script T_ScGlobal_LoopTR

And I can't find why and how to fix that (the game crashes after  I close the two windows)

**Comment by Assumeru** [comment]
You are loading Tamriel Data before the base game.
