### ISSUE TITLE
T_Dae_DngRuin_I_Mezzanine_01 UV stretching

### ISSUE THREAD

**Issue by Snailsting** [TD-Addon/TD_Addon#594]
A fairly trivial issue, but the UV coords on one corner of one of the bottom faces ain't what they're supposed to be

`tr\i\tr_in_dae_mezzanine_01.nif`

![Mezza](https://github.com/TD-Addon/TD_Addon/assets/120365872/c9af9efc-bae7-4df9-8286-45f698fd95d9)

**Comment by shtou23** [comment]
UV fixed
[Issue_594_fix.zip](https://github.com/TD-Addon/TD_Addon/files/14749770/Issue_594_fix.zip)
