### ISSUE TITLE
T_Glb_TerrWater_CurveFlw_512-01 and 02 wrong texture density

### ISSUE THREAD

**Issue by TillJohnM** [TD-Addon/TD_Addon#595]
Both variants of T_Glb_TerrWater_CurveFlw_512 have the wrong texture density when compared to other 512 Water pieces.

**Comment by antonisauren** [comment]
That one got fixed here https://github.com/TD-Addon/TD_Addon/commit/fc5928ac653948d876edebc18fb474e2254ba308
