### ISSUE TITLE
T_Imp_Newtscale_Cuirass_01 is identical to vanilla newtscale_cuirass

### ISSUE THREAD

**Issue by Revane-Crowford** [TD-Addon/TD_Addon#596]
They look the same and have the same stats. I don't see a need for the TD version to exist, especially now that typing "newt" into the search bar brings both the vanilla cuirass and all the TD pieces anyway. 
![newtscale](https://github.com/TD-Addon/TD_Addon/assets/126181577/da924809-5a90-404b-be33-eb521c029992)

**Comment by JackimoffWackimoff** [comment]
Deprecated, will need placements fixed in section
