### ISSUE TITLE
T_Imp_DngSewers_I_Stair_02 needs collision fix

### ISSUE THREAD

**Issue by Aveno2** [TD-Addon/TD_Addon#612]
Not fully walkable, requires jumping to ascend in parts

**Comment by antonisauren** [comment]
[pc_in_swrl_stair02.zip](https://github.com/TD-Addon/TD_Addon/files/15228187/pc_in_swrl_stair02.zip)

**Comment by antonisauren** [comment]
[pc_in_swrl_stair02.zip](https://github.com/TD-Addon/TD_Addon/files/15228324/pc_in_swrl_stair02.zip)
Or I checked wrong files. This one is better anyway.
