### ISSUE TITLE
CaveSH nede piece renames 

### ISSUE THREAD

**Issue by Aveno2** [TD-Addon/TD_Addon#616]
suggesting these so its clearer to developers what pieces are specific to nede burials so they aren't used accidentally, or copied across in retextures for other cave sets 

T_Mw_CaveSH_Hall_34 -> T_Mw_CaveSH_Hall_Ned1
T_Mw_CaveSH_Hall_11 -> T_Mw_CaveSH_Hall_Ned2
T_Mw_CaveSH_R_Side_04 -> T_Mw_CaveSH_R_Side_Ned1
T_Mw_CaveSH_R_Cor_06 -> T_Mw_CaveSH_R_Cor_Ned1
T_Mw_CaveSH_RockB_06 -> T_Mw_CaveSH_RockB_Ned1
T_Mw_CaveSH_RockB_07 -> T_Mw_CaveSH_RockB_Ned2
T_Mw_CaveSH_RockB_08 -> T_Mw_CaveSH_RockB_Ned3

**Comment by antonisauren** [comment]
There isn't anything nede-specific in them. Imo they could be used for any carved niche if needed.

**Comment by Aveno2** [comment]
they're specific insofar as the usecase is for nedic burials 
they could be used for other things, but shouldn't be as it'd detract from their intended use imo
