### ISSUE TITLE
Book batch fix

### ISSUE THREAD

**Issue by BlueshiftTR** [TD-Addon/TD_Addon#618]
Typos and inconsistencies in the following books, pasted from the site for more exposure:
File is on the site: (https://www.tamriel-rebuilt.org/bugtracker/book-batch-fix)
**Dunce in Morrowind**:
Deshaan -> Dejasyte
Verarchen -> Veranis
Baan Malur -> Blacklight
hearings -> hearing’s
Removed duplicate “and we”
generosity sera -> generosity, sera
but that's the position you're in, now, isn't it lad? -> But that's the position you're in now, isn't it, lad?
basically  practically -> practically
Removed double space
seemed to enjoyed -> seemed to enjoy
Moved comma inside quotation mark
All single hyphens used for interruptions -> double hyphens
Well thank you for noticing! -> Well, thank you for noticing!
of House Hlaalu sera -> of House Hlaalu, sera
fighters guild -> Fighters Guild
slip through the tracks -> slip through the cracks
marsh trained eye -> marsh-trained eye
This is the hub of our little wheel smoking gun. -> This is the hub of our little wheel.
he didn't have a writ of execution to present, we accidentally ended up in the Deshaan plains. Nobody would voluntarily go to the Deshaan plains. -> he didn't have a writ of execution to present, and we accidentally ended up in the Dejasyte. Nobody would voluntarily go to the Dejasyte.
Added a space after a comma
fighter's guild -> Fighters Guild
fighters guild -> Fighters Guild
Moved a period before a quotation mark
mages guild -> Mages Guild
and watched the sunset Sun Set -> and watched the sunset
who’s -> whose
**Ami-El**:
mothers -> mother’s
payed -> paid
Forvere -> Forever
Amet filled with holy purpose, apyed visit to the foster-father, who carved knives from bone -> Amet, filled with holy purpose, paid visit to the foster-father who carved knives from bone
loatshome -> loathsome
predator There -> predator. There
The, -> Then,
disuise -> disguise
**The Belharzareta**:
lendrs -> lenders
All single hyphens used for interruptions -> double hyphens
kothri -> Kothri
at these rumors though, -> at these rumors, though,
seemed to be the only thing that still seemed to animated -> seemed to be the only thing that still animated
Second “the jungle” -> it
**Codified Law, Volume 1**:
marukhati -> Marukhati
**The Siege of Kvatch**:
an smite my enemy -> and smite my enemy
jrighteousness -> righteousness
The Blood-Money Siege:
know -> known
**Fascicle 29-31**:
Darknes -> Darkness
**Funerary Rites of Cyrodiil**:
All single hyphens used for interruptions -> double hyphens
Put period inside quotation marks
did not come natural to -> did not come naturally to
means or internment -> means of interment
a suitable riverways -> suitable riverways
embalmement -> embalmment
Removed double space
was then top find -> was then to find
All instances of internment -> interment
**The Grand Alliance**:
All single hyphens used for interruptions -> double hyphens
All instances of Makh -> Mahk
Falkirstad -> Snowhawk
Put comma inside quotations
Removed space before comma
**The Imperial Kitchen, Volume 1**:
Imperial Minced meat -> Imperial Minced Meat
**Industries of the Niben**:
Slaugterfish -> Slaughterfish
from of currency -> form of currency
perfumer’s -> perfumers’
**Narrative of Yilgamseh**:
All single hyphens used for interruptions -> double hyphens
Added a quotation mark
Added a period
"What can I do to win eternal life," -> "What can I do to win eternal life?"
**Lex Imperii, Volume 2**:
a a -> a
**The Line of Emperors**:
All single hyphens used for interruptions -> double hyphens
todays -> today’s
SUCESSION -> SUCCESSION
Cuclecain -> Cuhlecain
Cuhlecian -> Cuhlecain
councel -> counsel
Kyntyra -> Kintyra
Kyntira -> Kintyra
Wayrestm neither -> Wayrest, neither
ELder -> Elder
COuncil -> Council
on the Eloisa’s only son -> on to Eloisa’s only son
Put periods and commas inside quotation marks
**Raid on Pyandonea**:
All single hyphens used for interruptions -> double hyphens
Removed random numbers
a an -> an
Removed an unnecessary comma
could not do thus -> could not do so
the new the King -> the new King
**Seven Families, Volume 1**:
Still they remain -> Still, they remain
**Songs of the Reaver Clans, Volume 3**:
Single hyphen used for interruption -> double hyphen
Moved period inside quotation mark
**Tales of the Woven City, Part 2**:
Korthingi -> Kothringi
**Talhjolde**:
All single hyphens used for interruptions -> double hyphens
Added periods to quotes
Moved periods inside quotation marks
Removed a few quotation marks where they didn’t make sense
**The Talking Guar of Vhul**:
All single hyphens used for interruptions -> double hyphens
Moved period inside quotation mark
**The Torment of Klausein**:
Replaced all instances of . . . with ...
I am sorry my lord -> I am sorry, my lord
**The Wealth of Wayrest**:
1Gua -> Gua 1
Occuring -> Occurring
skyrim -> Skyrim
you are mislead -> you are misled
high rock -> High Rock
cybiades -> Cybiades
Hail High Rock -> Hail High Rock.
devine -> divine
the empire funds -> the Empire’s funds
To often traveled -> Too often traveled
Sol1 and Sol2 -> Sol 1 and Sol 2
empire -> Empire
my ancestors -> my ancestors’
How can a group of so Troubled -> How can a group so Troubled
What news bring you of the west -> What news bring you of the west?
nords -> Nords
rain’s hand -> Rain’s Hand
Com1 and Com2 -> Com 1 and Com 2
Did not do anything about **Varieties of Thought**, but it needs a complete rewrite, and in the meantime I’d rather it just be deprecated.
**Voyage of the Three Winds**:
All single hyphens used for interruptions -> double hyphens
**Xahxes’ Gift, Part Three**:
Changed single quotes to double quotes
'Do not waste our time, fiend" said Orc-Friend Trini -> “Do not waste our time, fiend,” said Orc-Friend Trini.

**Comment by JackimoffWackimoff** [comment]
Merged fix
