### ISSUE TITLE
The light and particles on the large ebony candlesticks are borked

### ISSUE THREAD

**Issue by Snailsting** [TD-Addon/TD_Addon#633]
Concerns:
Meshes\tr\l\tr_l_ebonycandle_2.nif
Meshes\tr\l\tr_l_ebonycandle_2_pur.nif
Meshes\tr\l\tr_l_ebonycandle_2_red.nif

I think it's simply because everything is spread out between two different root nodes 

![Morrowind 2024-06-11 18 06 46 245](https://github.com/TD-Addon/TD_Addon/assets/120365872/2a18a245-83ca-4352-b85a-bf1a05704788)

**Comment by Snailsting** [comment]
Fix posted to: https://www.tamriel-rebuilt.org/asset/assorted-model-fixes-sep-2024

**Comment by antonisauren** [comment]
https://github.com/TD-Addon/TD_Addon/commit/4eb16e28d320ad72b9c924f966f4dacc641d4f4d
