### ISSUE TITLE
The hooks on PI's hanging fish containers still point to Lyithdonea textures

### ISSUE THREAD

**Issue by Snailsting** [TD-Addon/TD_Addon#642]
The hooks on `Meshes\pi\o\pi_cont_fish_jdhrnfsh1.nif` and `Meshes\pi\o\pi_cont_fish_slvrspde1.nif` are currently set to use `textures\az\bar_rusty_metal.dds `

**Comment by C3pa** [comment]
Does Tamriel Data have an equivalent of `textures\az\bar_rusty_metal.dds`.

**Comment by JackimoffWackimoff** [comment]
Fixed
