### ISSUE TITLE
Changes to PC road signs

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#650]
New signs needed:
- Hal Verovar (light wood)
- Thyra (light wood)
- Salthearth (light wood)
- Hal Belletor (light and dark wood)
- Marav (light wood)
- Delodiil (light and dark wood)
- Chorrol (light and dark wood)
- Sancre Tor (light and dark wood)
- Artemon (light and dark wood)
- Falkreath (light and dark wood)
- Rihad (light wood)
- Arenthia (light and dark wood)

Please add both the metal-rimmed and non-rimmed versions of each

Changes needed:
- Richton Estate -> Richtonhal
- Linchal Estate -> Linchal
- Fix Deathagrad -> Dethagrad

Deprecations:
- Brena Crossing Fort
- Fort Istirus
- Fort Ontus
- Fort Strand
- Hastrel Estate
- Wariel Estate

**Comment by JackimoffWackimoff** [comment]
Done
