### ISSUE TITLE
Error in global Cook and Fisherman my trade entry

### ISSUE THREAD

**Issue by Revane-Crowford** [TD-Addon/TD_Addon#651]
The current entry reads

_I am a cook. I prepare meals with ingenuity and skill, and I keep those around me happy with full bellies. I'm adept at using knives and hammers, skills I use to prepare meats **and and** tenderize them to perfection. With the right ingredients, I can even imbue food with minor alchemical effects._

The bolded "and and" is the main error, although I would also suggest another change: "adept at using knives and hammers, skills I use to"->"proficient with knives and hammers, skills I use to" to avoid repeating "use".

So my suggestion is:

_I am a cook. I prepare meals with ingenuity and skill, and I keep those around me happy with full bellies. I'm proficient with knives and hammers, skills I use to prepare meats and tenderize them to perfection. With the right ingredients, I can even imbue food with minor alchemical effects._

**Comment by Revane-Crowford** [comment]
Similar issue in the my trade for the global fisherman class, which reads

_I'm a fisherman. I use nets **ands** rods to catch fish to feed my family and to sell at the market. I sometimes fish at the shore, but most of the time I'm out in my boat. I know all the currents and where the fish will be at any time of the day or night._

ands->and

**Comment by JackimoffWackimoff** [comment]
Fixed
