### ISSUE TITLE
Seam on T_Bre_GreenGlassVase_02.nif

### ISSUE THREAD

**Issue by Toma400** [TD-Addon/TD_Addon#659]
Seam on `T_Bre_GreenGlassVase_02.nif` file:
![image](https://github.com/user-attachments/assets/039e9dc0-61ad-4ed8-9905-f7628af68433)

Fixed by Liliana ([original message](https://discord.com/channels/261789910594355200/1249611354357239888/1260921159982125147)):
> [hr_misc_gglass_vase_02.zip](https://github.com/user-attachments/files/16289830/hr_misc_gglass_vase_02.zip)

**Comment by Kynesifnar** [comment]
This was already merged.
