### ISSUE TITLE
T_Glb_Flora_WtHyacint02 not using blue flower texture

### ISSUE THREAD

**Issue by MinerMan60101** [TD-Addon/TD_Addon#667]
`pc\o\pc_flora_hyacinthB.nif` should be using the texture `pc_flora_whyb.dds` instead of `pc_flora_why.dds`.

**Comment by Kynesifnar** [comment]
pc_flora_hyacinthB.nif isn't even using pc_flora_why.dds and switching its flower texture to pc_flora_whyb.dds naturally causes issues.
