### ISSUE TITLE
Containers missing Graphic Herbalism support

### ISSUE THREAD

**Issue by BarbedWireKisses** [TD-Addon/TD_Addon#672]
As well as https://github.com/TD-Addon/TD_Addon/issues/580#issue-2141159050 - Roridomyces Phyllostachydis (T_Mw_FloraOW_Glwshrm_xx), Drumpear (T_Mw_FloraSH_Drumpear_xx), Sea Biscuit (T_Glb_Fauna_SeaBiscuitx) and Dusky Parrotfish (T_Glb_Fauna_FishSch_Dpf) all lack graphic herbalism support.

**Comment by HalfEnder776** [comment]
There are some more here as well https://github.com/TD-Addon/TD_Addon/issues/580#issue-2141159050

**Comment by antonisauren** [comment]
tr/f/tr_f_glowshroom_01.nif
tr/f/tr_f_glowshroom_02.nif
tr/f/tr_f_glowshroom_03.nif
tr/f/tr_f_glowshroom_04.nif
tr/f/tr_f_glowshroom_05.nif
tr/f/tr_flora_drumspear_01.nif
tr/f/tr_flora_drumspear_02.nif
tr/f/tr_flora_drumspear_03.nif
tr/f/tr_flora_drumspear_04.nif
tr/f/tr_flora_drumspear_05.nif
tr/f/tr_flora_drumspear_06.nif
pi/o/pi_f_sanddollarlive_01.nif
pi/o/pi_f_sanddollarlive_02.nif
pi/o/pi_f_sanddollardead.nif
pi/o/pi_cont_fschool_prrtfi.nif

**Comment by antonisauren** [comment]
Sea Biscuits were blacklisted in GH config on my end for some reason. Likely there was some messup in prior lua addon. All meshes had proper GH support already
