### ISSUE TITLE
`HfCom` containers instead of `HamCom`

### ISSUE THREAD

**Issue by Toma400** [TD-Addon/TD_Addon#677]
There are few containers following incorrect `Hf` prefix for Hammerfell instead of `Ham` suggested by guidelines. Since those assets were just recently merged, they should have no instances in the world, which hopefully would make the ID change easier:

- T_HfCom_Var_Bl1Empty
- T_HfCom_Var_Bl2Empty
- T_HfCom_Var_Cr1Empty
- T_HfCom_Var_Cr2Empty
- T_HfCom_Var_Cr3Empty
- T_HfCom_Var_Cr4Empty
- T_HfCom_Var_Cr5Empty

Additionally, there's also `T_HFCom_Furn_Ch2MGuild` with similar issue that I didn't want to report earlier, but now makes total sense to also change its ID, just so there's no possibility to base the new assets on TD precedence.
Note though, the last asset is probably put somewhere in section files, so would need checking at least Cyr_Main/PC_Sutch (maybe TR section files too, but not sure) and could have also potentially show up in Hammerfell project files, though not sure how this one could be handled before we get proper section files.

**Comment by JackimoffWackimoff** [comment]
Fixed
