### ISSUE TITLE
Shard of Vehemence and Neb's Talon ID changes

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#679]
Please change T_Nor_UNI_ShardOfVehemence -> T_Bre_UNI_ShardOfVehemence and T_Nor_UNI_NebsTalon->T_Rga_UNI_NebsTalon
These are Breton and Redguard artifacts, respectively, and both will be used in the SOTS release of HR427.

**Comment by Taniquetil24** [comment]
Updated issue desc to also include Neb's Talon

**Comment by JackimoffWackimoff** [comment]
Fixd
