### ISSUE TITLE
Please change the IDs of T_Hr_Cave**_I_4way_Room_01 to normal cave shell ones

### ISSUE THREAD

**Issue by Snailsting** [TD-Addon/TD_Addon#680]
It's pretty minor, but afaik they're not used anywhere yet so changing them shouldn't cause any issues at this point

Ideally the IDs of T_Hr_Cave**_I_4way_Room_01 (hr\i\hr_in_cv**_4room) would be changed to T_Hr_Cave**_I_Shell_26 so that they're consistent with the other cave shells
As it is, for all intents and purposes, just another one of those

The ID comes from the original CaveMold piece that made it into Data with a somewhat non-standard ID for a cave shell
Though save for PI's sets, the other retextures of it so far already follow the normal cave shell IDs anyway

**Comment by JackimoffWackimoff** [comment]
Fixd
