### ISSUE TITLE
T_Imp_SetGCPoor_I_House_02 Issues

### ISSUE THREAD

**Issue by sander798** [TD-Addon/TD_Addon#685]
A few complaints about T_Imp_SetGCPoor_I_House_02 / pc\i\PC_In_GC_House2.nif:

1. There appears to be a small part of the wall that pokes out into one of the window frames (right side, facing the door from centre).

![badhouseint](https://github.com/user-attachments/assets/83433528-2719-4546-ad8e-a19009f61061)

2. The central pillar is unusually easy to get caught on while moving past it, both in vanilla and OpenMW. This is most notable when moving against it going straight ahead from the window mentioned above towards the other side, which actually causes the player to be unable to move past it.

**Comment by antonisauren** [comment]
Central pillar was pentagon, changed it to octagon. You still get caught on it. It's just how tes3 collision works.
