### ISSUE TITLE
Draugr Lords can't cast Summon BoneWolf

### ISSUE THREAD

**Issue by SenebAnkh** [TD-Addon/TD_Addon#69]
The summon bonewolf spell, to be cast, seems to require a certain bloodmoon quest to be completed. So if you go in Skyrim before doing Bloodmoon, Draugr Lords will fail over and over to cast the summon, until being magicka depleted.
creature : T_Sky_Und_DrgrLor_01
spell : bm_summonbonewolf

**Comment by Assumeru** [comment]
Cannot reproduce. The draugr casts bm_draugr_curse until it runs out of magicka and never even attempts to summon a bonewolf.

I'm not sure creatures can even cast summon spells.

**Comment by SenebAnkh** [comment]
I was testing in OpenMW to be honest. But if it is not a problem in the vanilla engine, pretty sure it is not a big deal for now.

**Comment by Assumeru** [comment]
In OpenMW (0.46 and the current 0.47) it successfully casts the summon for me.

Maybe you've got a dirty mod messing with the spell? Can you cast it?

**Comment by SenebAnkh** [comment]
I cannot, so I may have a dirty mod, you're right
