### ISSUE TITLE
T_Bre_SetOstR_X_House_05 is missing some collision on roof

### ISSUE THREAD

**Issue by KittyKnowNothing** [TD-Addon/TD_Addon#691]
![missingcollision](https://github.com/user-attachments/assets/4889eb77-cb45-4cb8-9e63-8761b0c5374f)

highlighted faces are missing collision

HR/x/hr_OstR_house_05.nif

**Comment by FremennikMods** [comment]
This has been fixed here https://www.tamriel-rebuilt.org/asset/various-asset-improvements

**Comment by Snailsting** [comment]
The above fix was merged in https://github.com/TD-Addon/TD_Addon/commit/f429a44008fcaa0424385a66817b82e65084dbca
