### ISSUE TITLE
T_Imp_LegionMw_I_HelixRail_02 Has Missing Faces

### ISSUE THREAD

**Issue by sander798** [TD-Addon/TD_Addon#693]
![badrail](https://github.com/user-attachments/assets/5bd3ddce-6777-4f48-8518-a2adb9f5063a)

This is seen on both sides of the front inside post.

**Comment by Snailsting** [comment]
I suppose there'd be no real harm in adding those faces anyway, but the issue here isn't on the asset side. That's just not how those railings are supposed to be used

**Comment by sander798** [comment]
Fair enough, but someone did for a past TR release.

**Comment by sander798** [comment]
> I suppose there'd be no real harm in adding those faces anyway, but the issue here isn't on the asset side. That's just not how those railings are supposed to be used

Fair enough, but someone already did for a past TR release.

**Comment by antonisauren** [comment]
There is only this one not intended usage in TR, What piece is supposed to fit in there besides staircase. I can't find fitting railing piece. Is it for stacked starcases?
T_Imp_LegionMw_I_HelixRail_01 with pole in the center has the same issue.
I did lower part but it might not be the best idea. Rather that MG usage should be nuked or replaced with bespoke railing pieces.
[tr_in_impsmall_helmid.zip](https://github.com/user-attachments/files/17358311/tr_in_impsmall_helmid.zip)

**Comment by Snailsting** [comment]
HelixRail_02 is indeed used for stacked helix stairs yes, the spots with the open geometry are supposed to line up with the railings on those stair tiles
And adjusting the helix rails for that one cobble in Nivalis probably isn't the best way to go about it no

![Railing](https://github.com/user-attachments/assets/130a5eb3-2937-4119-8c10-7157fc094281)
