### ISSUE TITLE
T_Nor_Toadscale_Boots_02 uses the wrong mesh

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#694]
I made a mistake in setting up the esp for this set. The 02 variant of the toadscale boots is supposed to use the painted ankle mesh sky_a_toad_boot_p_a.nif, but it is currently using the unpainted version instead.

**Comment by JackimoffWackimoff** [comment]
Also swapped the body meshes over to the 02 variant
