### ISSUE TITLE
Cataphract Mail Cuirass goes invisible when worn underwater

### ISSUE THREAD

**Issue by BarbedWireKisses** [TD-Addon/TD_Addon#696]
T_Imp_GuardTown1_Cuirass_01 goes invisible when worn underwater. This applies to both the players and NPCs.

![Morrowind 2024-09-26 22 55 22 175](https://github.com/user-attachments/assets/2eb383fb-519f-4804-9f81-4a43c41f3b2d)
![Morrowind 2024-09-26 22 56 11 348](https://github.com/user-attachments/assets/3cd2f68e-157b-4688-b885-28742f26a0fe)

**Comment by antonisauren** [comment]
Armor uses alpha blend on chainmail, but changing it to alpha test does not fix an issue for me.
