### ISSUE TITLE
Typos in t_bk_confessionsofathieftr

### ISSUE THREAD

**Issue by johnaaron-git** [TD-Addon/TD_Addon#70]
**Version with typos, hanging commas, and subject predicates fixed is pasted below. I tried really hard to preserve the tone of the original, slang included. The Tamriel Rebuilt revised version can be found here to see/take a textdiff:**
https://en.m.uesp.net/wiki/Tamriel_Data:Confessions_of_a_Thief

I'm a thief. Now, don't get me wrong. I ain't saying this out of pride, but I ain't ashamed of my occupation neither. Thieves got a perfect right to exist in the Empire. People say we're dishonest. Of course, those people are usually either merchants or priests, which really gets me. Like a snake calling a worm ‘legless’.

Rulers like us. Crime in moderation is good for the economy. The trick is to keep it at a good, even pace with well-timed lulls to keep the fat bottoms from becoming complacent. Of course, the stupid thieves will keep stealing, empty their pockets, and steal some more. This ain't good for no-one. That's where the guilds come in.

The Thieves Guild is what they call a crime regulator. We protect each other and punish the clumsy and greedy. The kings depend on us to keep amateurs out of business.

Yeah, occasionally a king will come down on us. I've even seen a Guildmaster get himself stuck in prison once or twice. A cohort of mine said her first Guildmaster got himself hanged. If that happens, we have to get dirt on the king. Let me tell you, it ain’t pretty.

I got into the guild the way I've seen most thieves do it. It was a few years back, when that bully Jagar Tharn was sitting on the throne and everyone thought he was the Emperor. My parent’s farm got turned into eight acres of dust and rock, and they threw me and my brothers out. I was always thin, but by the time we made it to the closest town, I had become a good deal skinnier.

The town had some dirt that plants could grow in, but it didn't make them any richer than us. I tried to get all kinds of jobs, but the more desperate I became, the faster I’d get kicked out. When the rainy season finally came, it came like a sea and I didn't have nowhere to stay. Luckily, I found an unlocked cellar door.

Turns out that the owners of the house slept like old dogs, because I robbed them blind and they never even woke up. I sold it all to a shady merchant I knew and spent the next two days living like a potentate. Then I got my first visit from the Guild.

I remember what he looked like, but not what he said. Something like, "Hey kid, if you want to steal in these parts, you're going to have to join the Thieves Guild. Otherwise, someone like me is going to break your skinny arms so you can't steal."

I've known some people who refused membership in the Guild and kept on stealing. I've broken some of their arms myself. 

For me, it was my first career offer since my pa told me that if I didn't milk the cow, he'd rip my head off. By comparison, this guy at the tavern was almost a gentleman. I agreed right away.

Sure, I had to prove my worth to the Guild before I could join. But having two working arms is only part of the benefit: they trained me, taught me, and kept me out of prison. How many other guilds boast a forgery expert on the premises?

So, the next time you're calling some swindling merchant or usurious priest a thief, think about it. There is honor among thieves -- I should know.

**Comment by jamrt** [comment]
Just before I merge this text fix: this is a Daggerfall book and there are a TR version (with some typos fixes) and SHotN version.
I'll apply this fix (plus another typo correction or two) to both.
