### ISSUE TITLE
Riverfolk female 1st person hands use the male meshes

### ISSUE THREAD

**Issue by Kynesifnar** [TD-Addon/TD_Addon#702]
I'm not sure why; perhaps it has something to do with the 1st person male hands mesh not quite being named as it should?

**Comment by antonisauren** [comment]
Not only hands but wrists are also male in first person, despite being rigid mesh that ignores naming conventions.

**Comment by antonisauren** [comment]
After looking into it further, it happens even for vanilla races. Likely engine bug fixed in openMW.

**Comment by antonisauren** [comment]
It happens when you call enableracemenu. Fixes itself after save and reload. That command does not reload nifs in vanilla engine.
