### ISSUE TITLE
The file paths for all objects in the Skyrender int set are wrong

### ISSUE THREAD

**Issue by Snailsting** [TD-Addon/TD_Addon#703]
They all still point to the pre-review names for the models and the nest cells are currently missing from the esm all together

Judging by Chefs comment here https://www.tamriel-rebuilt.org/comment/36987#comment-36987 I suspect it might just be a case of the wrong version of the esp getting bundled with the R4M archive

**Comment by JackimoffWackimoff** [comment]
fixd
