### ISSUE TITLE
Fort Heath lacks a pc_furn_signpost_02 variant

### ISSUE THREAD

**Issue by BarbedWireKisses** [TD-Addon/TD_Addon#711]
There should be two variants of each signpost location for P:C, while Fort Heath has only one, the version which uses pc_furn_signpost_01. A pc_furn_signpost_02 variant is needed to point towards Fort Heath from Anvil, which is used in directions for quests.

![image](https://github.com/user-attachments/assets/6c77fa6e-7227-432e-8c60-38b56fc8b2cb)

**Comment by JackimoffWackimoff** [comment]
Fixed
