### ISSUE TITLE
T_Imp_DngRuinCyr_I_RoundStr_01 and _02 not traversable

### ISSUE THREAD

**Issue by Tiglath123** [TD-Addon/TD_Addon#714]
Meshes\pc\i\pc_in_impruin_rns_01 and 02. 
I can go down fine but can't go back up without awkwardly hugging the wall. NPCs have no chance. Vanilla engine.

**Comment by antonisauren** [comment]
Just forced triangulation of floor collider to go one way. Player goes smoothly. Enemies without pathgrid get stuck on walls but are able to get on top at the end.
