### ISSUE TITLE
T_Rga_SetHarbor_ShipIn_01 downstairs inaccessible

### ISSUE THREAD

**Issue by Revane-Crowford** [TD-Addon/TD_Addon#722]
You can't go to the lower deck of T_Rga_SetHarbor_ShipIn_01 / in_rga_ship_01.nif

Tested on female Breton. Visually there seems to be enough space, but something invisible is in the way. It works when they're underwater and you're swimming, but not when you're walking.

**Comment by Revane-Crowford** [comment]
If the Z-rotation on the hull is 90 then it works. It doesn't work flawlessly, though, it's still a bit awkward, so it's possible that there's room for improvement on the collision mesh. But it's not as critical of an issue as I thought it was.

**Comment by antonisauren** [comment]
https://github.com/TD-Addon/TD_Addon/commit/e9ba143ee31750dfa15666e7da51537f6d049fdd
