### ISSUE TITLE
T_Imp_GuardTown1_Boots_01 are too low

### ISSUE THREAD

**Issue by sander798** [TD-Addon/TD_Addon#724]
The boots worn by the Anvil city guard sink into the ground when worn by NPCs or the player, making the feet of guards look flat. 
![Morrowind 2024-10-22 14 23 30 671](https://github.com/user-attachments/assets/c66de0c3-a75f-44db-8293-8a1be1f3ef61)

**Comment by antonisauren** [comment]
Whole armor is in single nif. Every part is skinned to some BB skeleton with fucked up proportions.
Cuirass gets wrecked when import to blender so I can't export it in such state even after fixing that part in theory. Imo whole armor set calls for redo to vanilla standards.
