### ISSUE TITLE
T_Imp_SetAnv_X_AddonArchway_04 Has UV Issue

### ISSUE THREAD

**Issue by sander798** [TD-Addon/TD_Addon#727]
![Morrowind 2024-10-23 23 14 31 412](https://github.com/user-attachments/assets/85d1c526-5075-490f-8b9c-d5a64303425a)

**Comment by Snailsting** [comment]
It has some missing faces as well
![mISSING FACES](https://github.com/user-attachments/assets/d1a456d6-5d38-4297-bd64-478fb0d3f519)
