### ISSUE TITLE
T_Cnq_Ngopta should be T_QyK_Ngopta

### ISSUE THREAD

**Issue by Toma400** [TD-Addon/TD_Addon#729]
`T_Cnq_Ngopta` is incorrect ID from old times that should be reIDed to `T_QyK_Ngopta`, following correct culture ID for Keptu-Quey

**Comment by Toma400** [comment]
More old/incorrect IDs from Iterator:
- `T_QC_Furn_Urn_01` -> `T_QyC_Furn_Urn_01`
- `T_QC_Furn_Urn_02` -> `T_QyC_Furn_Urn_02`
- `T_QC_Furn_Urn_03` -> `T_QyC_Furn_Urn_03`
- `T_QK_Furn_Urn_01` -> `T_QyK_Furn_Urn_01`
- `T_QK_Furn_Urn_02` -> `T_QyK_Furn_Urn_02`
- `T_QK_Furn_Urn_03` -> `T_QyK_Furn_Urn_03`

**Comment by RonikTR** [comment]
> More old/incorrect IDs from Iterator:
> 
>     * `T_QC_Furn_Urn_01` -> `T_QyC_Furn_Urn_01`
> 
>     * `T_QC_Furn_Urn_02` -> `T_QyC_Furn_Urn_02`
> 
>     * `T_QC_Furn_Urn_03` -> `T_QyC_Furn_Urn_03`
> 
>     * `T_QK_Furn_Urn_01` -> `T_QyK_Furn_Urn_01`
> 
>     * `T_QK_Furn_Urn_02` -> `T_QyK_Furn_Urn_02`
> 
>     * `T_QK_Furn_Urn_03` -> `T_QyK_Furn_Urn_03`

These are all already deprecated, so no action is neeed
