### ISSUE TITLE
T_Ayl_DngRuin_X_Pedestal_01 is Far Too Easy to Get Caught On

### ISSUE THREAD

**Issue by sander798** [TD-Addon/TD_Addon#738]
Merely walking into the central part of the pedestal straight on is enough to get stuck to the point of needing to use tcl.

This can be tested at e.g. Garlas Malatar.

**Comment by Snailsting** [comment]
pc\x\pc_ex_ar_pedestal01.nif

It's just a simple case of an inverted collision mesh
