### ISSUE TITLE
All Ayleid scrolls in T_D are way too heavy

### ISSUE THREAD

**Issue by BarbedWireKisses** [TD-Addon/TD_Addon#741]
All magical scrolls in both vanilla and data weigh 0.2, except for the Ayleid scrolls, which all weigh 2.50. There doesn't seem to be any reason for this so their weight should probably be brought down to match the others.

![image](https://github.com/user-attachments/assets/af32a27a-bda1-445e-b5c0-0e22b7b04c00)

**Comment by Yoae-bo** [comment]
[this asset](https://www.tamriel-rebuilt.org/asset/ayleid-scroll) should take care of this problem, the new Ayleid scrolls look heavier than the vanilla ones, justifying the 2.5 weight
