### ISSUE TITLE
T_Rga_SetHarbor_Ship_01 Has Flickering Decals

### ISSUE THREAD

**Issue by sander798** [TD-Addon/TD_Addon#742]
These eye things flicker very noticably in-game. They should probably be moved out a ways from the hull (even though it looks weird up close; exact distance needs in-game testing), somehow made a part of the hull itself, or simply removed in favour of a separate reference with the same image to be placed in the same spot.

![boateye](https://github.com/user-attachments/assets/e0aa8e78-c485-47f0-9772-36ee72cf0241)

**Comment by hemaris-tr** [comment]
fixed in commit [64117a2](https://github.com/TD-Addon/TD_Addon/commit/64117a26242e1f3cde151b6b037cd2e7904deeb4)
