### ISSUE TITLE
Diseased Colovian Bears move at impossibly low speed due to Dampworm

### ISSUE THREAD

**Issue by Revane-Crowford** [TD-Addon/TD_Addon#745]
They essentially start hovering in mid-air while """"running"""" at you. Dampworm drains Speed 10-30, and the bears (**T_Cyr_Fau_BearColDs_01**) have a speed stat of only 15. There needs to be some workaround for them to be used. 
Either:
- Fake buff their base speed stat so it's normal-ish after the disease.
- Make some scripting solution that makes them spread the disease without technically having it.
- Give them a different disease.

**Comment by antonisauren** [comment]
Well, it is true for many vanilla beasts too.

**Comment by Revane-Crowford** [comment]
It's true for 2 vanilla creatures. The unique Blighted Kwama Warrior that only appears in one mine, and the Ascended Sleepers where it's less noticeable because they move around shufflingly anyway, and even there it's clearly an oversight. No other speed-affecting disease is given to a creature with a base stat so low it can become zero.

**Comment by BlueshiftTR** [comment]
Fixed with https://www.tamriel-rebuilt.org/asset/td-edits-bugs
