### ISSUE TITLE
New wines should be added to Altmer wines list

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#747]
Please add the three new Altmer drinks from [this merged claim](https://www.tamriel-rebuilt.org/asset/si-altmer-wines) to T_Sum_Random_Drinks

**Comment by Toma400** [comment]
Fixed [in this reviewed claim](https://www.tamriel-rebuilt.org/asset/new-altmer-drinks-added-lvl-list), can be closed.
