### ISSUE TITLE
There are visible black bars on the icon for T_Bk_DeSphaeraNirniPC

### ISSUE THREAD

**Issue by BarbedWireKisses** [TD-Addon/TD_Addon#752]
The in-game icon for T_Bk_DeSphaeraNirniPC (pc/m/pc_bk_book_16.nif) has visible black bars.

![Morrowind 2024-11-10 14 28 47 013](https://github.com/user-attachments/assets/bff86109-3cc9-4733-9fcd-337324ba3ba5)

**Comment by antonisauren** [comment]
Every single PC book icon is saved as DXT1 with mipmaps.
