### ISSUE TITLE
Hanging orbs missing glowmaps

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#762]
Seems like the T_Com_Furn_HangingOrbs emit light but don't look illuminated ingame

**Comment by Snailsting** [comment]
Because for some reason somebody actually seems to have thought that it was a good idea to restrict the glow mapped versions to HD data

**Comment by Kynesifnar** [comment]
Cicero likes to remove glowmaps from SD assets. I think that it makes sense in some cases, but this is not one of them.
