### ISSUE TITLE
Alessian Gauntlets missing 1st person rigging

### ISSUE THREAD

**Issue by Yoae-bo** [TD-Addon/TD_Addon#765]
there's no .1st.nif file for alessian bronze armor, specifically for T_Imp_AlessianBrnz_GauntletL_01 and T_Imp_AlessianBrnz_GauntletR_01

**Comment by antonisauren** [comment]
Mesh is there with decent rigging (pc_a_alesb_gaunt.1st.nif). Just Body part in CS has 3rd person mesh assigned.

**Comment by RakanishuPT** [comment]
Fixed in https://github.com/TD-Addon/TD_Addon/commit/b2d80dbd5baefcf6ab8a0e9784a2ca976c4c4e76
