### ISSUE TITLE
Ayleid bridge pieces have bad normals

### ISSUE THREAD

**Issue by MinerMan60101** [TD-Addon/TD_Addon#767]
The series of models `pc\x\pc_ex_ar_bridge01.nif` have bad normals, resulting in weird diagonal lines on the objects.
![Ayleid_Bridge](https://github.com/user-attachments/assets/28ea1c94-7450-4998-83c7-e11923581f59)

**Comment by hemaris-tr** [comment]
Fixed by commit [69833e8](https://github.com/TD-Addon/TD_Addon/commit/69833e8a665738893fe00fb8c3fc8ec4807e06d4)
