### ISSUE TITLE
Piranha scaling issues in openMW

### ISSUE THREAD

**Issue by Yoae-bo** [TD-Addon/TD_Addon#771]
Adding to the problems reported in this issue https://github.com/TD-Addon/TD_Addon/issues/658

Piranhas in openMW 0.49 are scaled up to the size of their skeleton

Piranhas would make an appearance in the Abecean Shores release but it's unlikely that OpenMW will fix this issue in time for the AS release

**Comment by Assumeru** [comment]
The relevant OpenMW issue: https://gitlab.com/OpenMW/openmw/-/issues/4437
