### ISSUE TITLE
new weight and value for T_Ayl_Scrollcase_01

### ISSUE THREAD

**Issue by Yoae-bo** [TD-Addon/TD_Addon#777]
T_Ayl_Scrollcase_01 currently have a weight of 1 and value of 1

should weight 2 and have a value of 15

**Comment by TriWubbly** [comment]
[AS_ScrollcaseFix.esp.zip](https://github.com/user-attachments/files/18017617/AS_ScrollcaseFix.esp.zip)

**Comment by RakanishuPT** [comment]
Fixed in https://github.com/TD-Addon/TD_Addon/commit/b2d80dbd5baefcf6ab8a0e9784a2ca976c4c4e76
