### ISSUE TITLE
Colovian Household Sword should be more expensive

### ISSUE THREAD

**Issue by BarbedWireKisses** [TD-Addon/TD_Addon#781]
The Colovian Household Sword T_Imp_Col_House_Sword_01 is a rare status item of the Colovian nobility, but it costs only 70 gold, less than a standard steel longsword. The price should be raised significantly, my suggestion would be to at or around 500 gold.

![image](https://github.com/user-attachments/assets/e12b0045-f83d-45d3-86f3-561248987794)

**Comment by BlueshiftTR** [comment]
Fixed with https://www.tamriel-rebuilt.org/asset/td-edits-bugs
