### ISSUE TITLE
Remove "fortify potion" global response from TD

### ISSUE THREAD

**Issue by Revane-Crowford** [TD-Addon/TD_Addon#782]
Every other "X potion" response in vanilla was only filtered to particular people, but the fortify potion topic was randomly given to every trader and alchemist as well. This is an oversight that we shouldn't blindly copy. Especially for traders this is almost never fitting, and the entry is barely useful in the first place, and has incorrect information to boot.

Notably, it's only T_Glb_TraderService that TD filtered it to, not even the vanilla Trader and Trader Service classes used in mainland Morrowind.

**Comment by RakanishuPT** [comment]
Fixed in https://github.com/TD-Addon/TD_Addon/commit/b2d80dbd5baefcf6ab8a0e9784a2ca976c4c4e76
