### ISSUE TITLE
Spell T_Com_Mys_Insight is auto calculated

### ISSUE THREAD

**Issue by RonikTR** [TD-Addon/TD_Addon#785]
No spells added by T_Data (or any of the section files) should have auto calc enabled since it means the game will distribute them to all eligible NPCs, including vanilla NPCs.

**Comment by RakanishuPT** [comment]
Fixed in https://github.com/TD-Addon/TD_Addon/commit/b2d80dbd5baefcf6ab8a0e9784a2ca976c4c4e76

**Comment by RakanishuPT** [comment]
Fixed in https://github.com/TD-Addon/TD_Addon/commit/b2d80dbd5baefcf6ab8a0e9784a2ca976c4c4e76
