### ISSUE TITLE
pc_ex_cpl_threshold1.nif LOD Distance is Too Short

### ISSUE THREAD

**Issue by sander798** [TD-Addon/TD_Addon#794]
The lighting and geometry can be very noticeably different on this base model v.s. the LOD but the distance at which they are swapped is too close for the player to miss the change. This might be partly due to my higher resolution display though.

This can be seen at the chapel on the docks of Anvil, depending on the time of day.

**Comment by Snailsting** [comment]
The LOD threshold is fine as it is, the difference in shading is just caused by some funky vertex normals on the near LOD

**Comment by antonisauren** [comment]
Wait, it's a foundation block with LOD reducing from 28 to 8 triangles. Making lod for such thing is ridiculous. What's the point? Swaping mesh costs more than rendering 20 triangles. Just throw whole lod away.
