### ISSUE TITLE
T_Ayl_DngRuin_X_OuterCircle_04 lacking collision in places

### ISSUE THREAD

**Issue by BarbedWireKisses** [TD-Addon/TD_Addon#799]
Parts of T_Ayl_DngRuin_X_OuterCircle_04 (pc\x\pc_ex_ar_outercircle04.nif) lack collision - see screenshots for the issue. It is understood that there's a separate Ayleid set collision issue, but that one doesn't deal with the specifics of this issue, which would be good to get sorted in time for the AS.

![Morrowind 2024-11-18 21 59 14 077](https://github.com/user-attachments/assets/4d28243c-b3ba-43b4-9974-8b180e804d46)
![Morrowind 2024-11-18 21 59 29 919](https://github.com/user-attachments/assets/a2a18486-c676-4378-ba3c-0e0d5a27ea94)

**Comment by Snailsting** [comment]
04 may have been fixed, but `pc\x\pc_ex_ar_outercircle01` to `07` all suffered from the same issue, so those still need to be taken care of
