### ISSUE TITLE
T_Glb_Sailor "my trade" edit

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#806]
current second sentence is a little awkwardly phrased, and not always accurate (some sailors are not part of crews)
> I'm a sailor. I work on a ship performing manual laboring tasks for my captain.
should become something like
> I'm a sailor. I work on a ship, where I rig sails, tie knots, swab decks, and take care of anything else that needs doing.

**Comment by cheflul** [comment]
In my data files folder for the upcoming final merge
