### ISSUE TITLE
banner_dondril

### ISSUE THREAD

**Issue by dondril** [TD-Addon/TD_Addon#81]
TES3Stream Warning: Model "Meshes\TR\f\Xtr_banner_dondril.NIF" tex not found "textures\tr\u\tr_banner_dondril.dds"!
I'm using the hd version with Tamriel rebuild 21.01

**Comment by MwGek** [comment]
Thanks for report, this is fixed in the next version.

**Comment by Assumeru** [comment]
Reopening because it's broken (again?) in 8.9.
