### ISSUE TITLE
Welkynd Spirit Death Particles

### ISSUE THREAD

**Issue by KnobelKnight** [TD-Addon/TD_Addon#813]
When a Welkynd Spirit dies on MWSE, if it has any particle effects in the air, they are left floating in place. Besides being visually confusing, as it sort of looks like it's still alive, it looks bad because the particles no longer animate.

On OpenMW, the particles instead drop to the ground after death, which looks much better.
![Elder Scrolls 3  Morrowind Screenshot 2024 12 17 - 16 35 24 35](https://github.com/user-attachments/assets/47a67608-e5d4-4948-a985-18c0adf3f052)

**Comment by antonisauren** [comment]
There are no visibility controllers on either particles or emitters. Should be easy to fix.
