### ISSUE TITLE
Airship wheel vibrates

### ISSUE THREAD

**Issue by Taniquetil24** [TD-Addon/TD_Addon#818]
The activator T_Imp_SetAirship_Wheel_01 seems to vibrate ingame, like it's trying to turn but is stuck on something

**Comment by antonisauren** [comment]
Works perfectly stable in test cell in oldwind. Does it vibrate when activated (Idle2) or when not touched (idle1)? Are you testing it in exterior space of Cyrodiil? Are you using openMW?
