### ISSUE TITLE
Werewolf head sometimes visible under Wereboar head

### ISSUE THREAD

**Issue by Glisptheglitchwasp** [TD-Addon/TD_Addon#82]
![Morrowind 2021-02-09 23 50 00 900](https://user-images.githubusercontent.com/78887755/107592543-3f5cfa80-6bdb-11eb-9419-a169dee0eaf6.png)

Sometimes (but not always) the werewolf head is visible underneath the wereboar head while PC is transformed.

**Comment by Alyst3r** [comment]
Pushed fix in internal data, I think it'll be merged with next TD_Addon update.
