### ISSUE TITLE
Circus tents use low resolution textures on the HD version of Data

### ISSUE THREAD

**Issue by BarbedWireKisses** [TD-Addon/TD_Addon#822]
Both interior and exterior meshes for the circus tents (T_Com_SetCir_X_Small_Green, T_Com_SetCir_X_Small_Purple etc) and possibly the large versions too which I couldn't check, seem to use low resolution textures on the HD version of data, causing very a noticeable difference in texture resolution in-game. See screenshot.

![Morrowind_2024-12-21_07 32 36 043](https://github.com/user-attachments/assets/f0b79d56-f467-4b52-bdaa-d733f9522a3b)

**Comment by Kynesifnar** [comment]
Oh yeah, I forgot to close this yesterday.
