### ISSUE TITLE
tr_aj_rock_02.dds missing from the ESM

### ISSUE THREAD

**Issue by RAINZFOXX** [TD-Addon/TD_Addon#86]
Warning from Distant Land Setup using MGE XE 0.11.6: Texture 'tr\lnd\tr_aj_rock_02.dds in plugin tamriel_data.esm failed to load (Object reference not set to an instance of an object.)

**Comment by Ellnz** [comment]
As the texture is not actually used anywhere ingame (as it has been removed) this error is inconsequential, and can be safely ignored.
