### ISSUE TITLE
Maps and guides use the wrong icon

### ISSUE THREAD

**Issue by charger24** [TD-Addon/TD_Addon#93]
I set the wrong scroll icon for the following maps and guides: 

Guide to Anvil
Guide to Dragonstar
Guide to Karthwasten
Guide to Old Ebonheart

They should be adjusted to use the same scroll icon as the vanilla "Guide to [XYZ]" scrolls.

Additionally, the "Map of the Gold Coast", "Map of the Telvanni Isles, and "Map of the Reach" could be changed to match as well, but those don't have a vanilla analogue, so it's up to the discretion of the Tamriel_Data admins whether to keep those icons distinct.

**Comment by jamrt** [comment]
Can't replicate this. They are all m\text_scroll_01.nif.

**Comment by jamrt** [comment]
Could not be replicated. might have something to do with some odd things in icons\m (different tga and dds icons).
