### ISSUE TITLE
T_Rea_Mys_Soultheft Typo

### ISSUE THREAD

**Issue by RakanishuPT** [TD-Addon/TD_Addon#94]
"Nahgacra's Soul Thef" is missing a "t", should be "Theft".

**Comment by RakanishuPT** [comment]
This is actually a spell, not a book.  Might be best to give it a different Name altogether since another spell has "Soul Theft" in the name, too.

**Comment by jamrt** [comment]
I changed it to "Nahgacra's Soul Heist".
