### ISSUE TITLE
Diseased Visual Effect

### ISSUE THREAD

**Issue by RakanishuPT** [TD-Addon/TD_Addon#95]
Some diseased animals have persistent visual effects above them, which I'm fairly certain is caused by a Drain Health effect (something not included in any vanilla disease).

These T_D spells have Drain Health:
- T_Dis_Bloodrot
- T_Dis_BrainFever
- T_Dis_ScarletFever
- T_Dis_StomachRot
- T_Dis_WitchesPox
- T_Dis_Woundrot
- T_Dis_YellowRot

Drain Magicka (haven't tested this one):
- T_Dis_Wizardfever

**Comment by cheflul** [comment]
Fixed in Dec 03 update
