### ISSUE TITLE
Character Model Graphical Bug

### ISSUE THREAD

**Issue by Frostmeat** [TD-Addon/TD_Addon#96]
Certain face files appear to be missing; NPCs/PCs attempting to be loaded into the game cause an error notification and severe visual artifacting. Specifically, giant yellow and blue semi-transparent polygonal shapes cover their character models. The game crashes almost-immediately afterward. 
I installed Tamriel Data, Tamriel Rebuilt, and Skyrim: Home of the Nords exactly as instructed via the appropriate mod pages with the latest builds of each and nothing I have tried seems to remedy this crashing issue. It's so severe I cannot leave the character creation screen; certain faces will cause the CTDs to happen even when simply viewed on the character building menu. 
This has been installed on a 100% fresh install of Morrowind: GotY Edition, with the only other modifications being Script Extender (latest build,) Morrowind Code Patch (latest build,) and Morrowind Graphics Extender (latest build.)

**Comment by Ellnz** [comment]
Sounds like you haven't properly registered the BSAs (as NPC/PC faces are the first additional assets to appear to the player).
